export const questions = [    
    { number: 1, text: "I enjoy reading scientific and technical literature", scales: ['5'], lang: 'en' },
    { number: 2, text: "I have a good appetite", scales: ['2'], lang: 'en' },
    { number: 3, text: "I usually wake up feeling fresh and rested in the morning", scales: ['2'], lang: 'en' },
    { number: 4, text: "I think I would enjoy working as a librarian", scales: ['5'], lang: 'en' },
    { number: 5, text: "The slightest noise wakes me up", scales: ['2'], lang: 'en' },
    { number: 6, text: "I enjoy reading about crimes in newspapers", scales: ['9'], lang: 'en' },
    { number: 7, text: "My hands and feet are usually warm enough", scales: ['1'], lang: 'en' },
    { number: 8, text: "My daily life is full of events that interest me", scales: ['2'], lang: 'en' },
    { number: 9, text: "My productivity is no worse than it used to be", scales: ['2'], lang: 'en' },
    { number: 10, text: "I often feel a 'lump' in my throat", scales: ['3', '7'], lang: 'en' },
    { number: 11, text: "I believe that dreams always come true", scales: ['9'], lang: 'en' },
    { number: 12, text: "I enjoy reading about crimes and mysterious adventures", scales: ['9'], lang: 'en' },
    { number: 13, text: "Work requires significant effort from me", scales: ['2', '7'], lang: 'en' },
    { number: 14, text: "The number of this item should be circled", scales: [], lang: 'en' },
    { number: 15, text: "Sometimes I have such unpleasant thoughts that it’s better not to talk about them", scales: ['L', '6'], lang: 'en' },
    { number: 16, text: "I feel that life has been harsh to me", scales: ['4', '6'], lang: 'en' },
    { number: 17, text: "My father is a good person", scales: ['F'], lang: 'en' },
    { number: 18, text: "I very rarely have constipation", scales: ['1'], lang: 'en' },
    { number: 19, text: "When starting a new job, I prefer to know who I should build good relationships with", scales: ['5'], lang: 'en' },
    { number: 20, text: "My sex life is satisfactory", scales: ['F'], lang: 'en' },
    { number: 21, text: "At times, I have very much wanted to leave home", scales: ['4', '6'], lang: 'en' },
    { number: 22, text: "At times, I have attacks of laughter or crying that I cannot control", scales: ['6', '7'], lang: 'en' },
    { number: 23, text: "I am bothered by attacks of nausea and vomiting", scales: ['1', '2', '3', '4'], lang: 'en' },
    { number: 24, text: "It seems to me that there is no one who understands me", scales: ['4', '6', '8'], lang: 'en' },
    { number: 25, text: "I would like to be a singer", scales: ['5'], lang: 'en' },
    { number: 26, text: "If I find myself in an unpleasant situation, it’s best for me to keep quiet", scales: ['3'], lang: 'en' },
    { number: 27, text: "At times, I feel under the power of some evil force", scales: ['F', '6'], lang: 'en' },
    { number: 28, text: "If I am treated unfairly, I feel I must retaliate just on principle", scales: ['4'], lang: 'en' },
    { number: 29, text: "I am bothered by heartburn several times a week", scales: ['1'], lang: 'en' },
    { number: 30, text: "Sometimes I feel like swearing", scales: ['L', 'K'], lang: 'en' },
    { number: 31, text: "Nightmares haunt me almost every night", scales: ['F'], lang: 'en' },
    { number: 32, text: "I notice it has become difficult for me to focus on a specific task or job", scales: ['2', '3', '4', '8'], lang: 'en' },
    { number: 33, text: "The number of this item should be circled", scales: [], lang: 'en' },
    { number: 34, text: "I have a cough most of the time", scales: ['F'], lang: 'en' },
    { number: 35, text: "If people didn’t plot against me, I would achieve much more", scales: ['F', '4', '6', '8'], lang: 'en' },
    { number: 36, text: "I rarely worry about my health", scales: ['2', '4'], lang: 'en' },
    { number: 37, text: "I have never had trouble due to my behavior related to sex life", scales: ['4'], lang: 'en' },
    { number: 38, text: "There was a time in my youth when I committed petty theft", scales: ['F', '8'], lang: 'en' },
    { number: 39, text: "At times, I feel like breaking things or smashing dishes", scales: ['K'], lang: 'en' },
    { number: 40, text: "I would prefer to spend most of my time sitting idle and daydreaming", scales: ['F', '8'], lang: 'en' },
    { number: 41, text: "I have had periods lasting days, weeks, or even months when I couldn’t take on any task because I couldn’t get started", scales: ['2', '7', '8'], lang: 'en' },
    { number: 42, text: "My family disapproves of the job I have chosen (or plan to choose)", scales: ['F', '4'], lang: 'en' },
    { number: 43, text: "My sleep is interrupted and restless", scales: ['1', '2', '3'], lang: 'en' },
    { number: 44, text: "I have a headache most of the time", scales: ['3'], lang: 'en' },
    { number: 45, text: "I do not always tell the truth", scales: ['L'], lang: 'en' },
    { number: 46, text: "My mind works better now than ever before", scales: ['2'], lang: 'en' },
    { number: 47, text: "Once a week or more, I am suddenly overcome by heat for no apparent reason", scales: ['3'], lang: 'en' },
    { number: 48, text: "The number of this item should be circled", scales: [], lang: 'en' },
    { number: 49, text: "It would be better if almost all laws were abolished", scales: ['F'], lang: 'en' },
    { number: 50, text: "At times, I feel like I am dying", scales: ['F'], lang: 'en' },
    { number: 51, text: "I often feel anxious", scales: ['2', '7'], lang: 'en' },
    { number: 52, text: "I get tired easily", scales: ['2', '8'], lang: 'en' },
    { number: 53, text: "It seems to me that people often talk about me behind my back", scales: ['F', '6'], lang: 'en' },
    { number: 54, text: "I rarely feel dizzy", scales: ['F'], lang: 'en' },
    { number: 55, text: "I am bothered by back pain", scales: ['1', '3'], lang: 'en' },
    { number: 56, text: "I sometimes feel insecure", scales: ['F'], lang: 'en' },
    { number: 57, text: "I rarely argue with people", scales: ['2', 'K'], lang: 'en' },
    { number: 58, text: "I find it hard to fall asleep", scales: ['2', '7'], lang: 'en' },
    { number: 59, text: "I enjoy lively company", scales: ['9'], lang: 'en' },
    { number: 60, text: "I do not always keep my promises", scales: ['L'], lang: 'en' },
    { number: 61, text: "I sometimes lose my patience", scales: ['4'], lang: 'en' },
    { number: 62, text: "I often have stomach pain", scales: ['1'], lang: 'en' },
    { number: 63, text: "The number of this item should be circled", scales: [], lang: 'en' },
    { number: 64, text: "I love being the center of attention", scales: ['9'], lang: 'en' },
    { number: 65, text: "I rarely have attacks of weakness", scales: ['F'], lang: 'en' },
    { number: 66, text: "The number of this item should be circled", scales: [], lang: 'en' },
    { number: 67, text: "I feel depressed", scales: ['2', '4', '8'], lang: 'en' },
    { number: 68, text: "I am bothered by joint pain", scales: ['1'], lang: 'en' },
    { number: 69, text: "I would like to become an artist", scales: ['5'], lang: 'en' },
    { number: 70, text: "I prefer quiet work", scales: ['5'], lang: 'en' },
    { number: 71, text: "I rarely lose my temper", scales: ['K'], lang: 'en' },
    { number: 72, text: "I have attacks of palpitations", scales: ['1'], lang: 'en' },
    { number: 73, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 74, text: "I do not like giving orders", scales: ['5'], lang: 'en' },
    { number: 75, text: "I always try to be polite", scales: ['L'], lang: 'en' },
    { number: 76, text: "I have chest pains", scales: ['3', '7', '8'], lang: 'en' },
    { number: 77, text: "I do not like to argue", scales: ['5'], lang: 'en' },
    { number: 78, text: "I prefer solitude", scales: ['5'], lang: 'en' },
    { number: 79, text: "I rarely feel sick", scales: ['5'], lang: 'en' },
    { number: 80, text: "Noisy people annoy me", scales: ['2'], lang: 'en' },
    { number: 81, text: "I do not like physical work", scales: ['5'], lang: 'en' },
    { number: 82, text: "I sometimes feel guilty", scales: ['4', '0'], lang: 'en' },
    { number: 83, text: "I rarely have headaches", scales: ['F'], lang: 'en' },
    { number: 84, text: "I sometimes act impulsively", scales: ['4'], lang: 'en' },
    { number: 85, text: "I am bothered by strange thoughts", scales: ['F'], lang: 'en' },
    { number: 86, text: "I often feel tired", scales: ['2', '7'], lang: 'en' },
    { number: 87, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 88, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 89, text: "I do not like change", scales: ['K'], lang: 'en' },
    { number: 90, text: "I always try to be honest", scales: ['L'], lang: 'en' },
    { number: 91, text: "I rarely quarrel with loved ones", scales: ['4'], lang: 'en' },
    { number: 92, text: "I do not like noise", scales: ['5'], lang: 'en' },
    { number: 93, text: "I am afraid of heights", scales: ['6'], lang: 'en' },
    { number: 94, text: "It seems to me that I am underestimated", scales: ['4', '7'], lang: 'en' },
    { number: 95, text: "I rarely cry", scales: ['2'], lang: 'en' },
    { number: 96, text: "I trust people", scales: ['K'], lang: 'en' },
    { number: 97, text: "I love being active", scales: ['8', '9'], lang: 'en' },
    { number: 98, text: "I am worried about my memory", scales: ['2'], lang: 'en' },
    { number: 99, text: "I do not like asking for help", scales: ['5'], lang: 'en' },
    { number: 100, text: "I easily get enthusiastic", scales: ['9'], lang: 'en' },
    { number: 101, text: "I rarely feel lonely", scales: ['9'], lang: 'en' },
    { number: 102, text: "I find it hard to make decisions", scales: ['4', '7'], lang: 'en' },
    { number: 103, text: "I rarely have back pain", scales: ['1'], lang: 'en' },
    { number: 104, text: "I often feel out of place", scales: ['2', '8'], lang: 'en' },
    { number: 105, text: "I do not like criticism", scales: ['L'], lang: 'en' },
    { number: 106, text: "I sometimes think about revenge", scales: ['4', '7'], lang: 'en' },
    { number: 107, text: "I am worried about my nerves", scales: ['2'], lang: 'en' },
    { number: 108, text: "I have leg pains", scales: ['1'], lang: 'en' },
    { number: 109, text: "I am afraid of the dark", scales: ['6'], lang: 'en' },
    { number: 110, text: "I sometimes feel unwanted", scales: ['4', '6'], lang: 'en' },
    { number: 111, text: "I believe in the supernatural", scales: ['6', '0'], lang: 'en' },
    { number: 112, text: "I rarely have a sore throat", scales: ['F'], lang: 'en' },
    { number: 113, text: "I do not like cleaning", scales: ['F'], lang: 'en' },
    { number: 114, text: "I am bothered by stomach pains", scales: ['1', '3'], lang: 'en' },
    { number: 115, text: "I rarely feel tired", scales: ['F'], lang: 'en' },
    { number: 116, text: "I do not like public speaking", scales: ['5'], lang: 'en' },
    { number: 117, text: "I sometimes think about death", scales: ['6', '0'], lang: 'en' },
    { number: 118, text: "I get irritated easily", scales: ['4'], lang: 'en' },
    { number: 119, text: "I rarely have nightmares", scales: ['F'], lang: 'en' },
    { number: 120, text: "I do not like large gatherings", scales: ['5'], lang: 'en' },
    { number: 121, text: "I am haunted by strange thoughts", scales: ['F', '6'], lang: 'en' },
    { number: 122, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 123, text: "I believe in predictions", scales: ['F', '6'], lang: 'en' },
    { number: 124, text: "I rarely feel pain", scales: ['K', '0'], lang: 'en' },
    { number: 125, text: "I have arm pains", scales: ['1'], lang: 'en' },
    { number: 126, text: "I love music", scales: ['5'], lang: 'en' },
    { number: 127, text: "I sometimes lose control", scales: ['4', '9'], lang: 'en' },
    { number: 128, text: "I do not like physical exercise", scales: ['3'], lang: 'en' },
    { number: 129, text: "I rarely feel weak", scales: ['K'], lang: 'en' },
    { number: 130, text: "I often feel sad", scales: ['2', '9'], lang: 'en' },
    { number: 131, text: "I am not bothered by my dreams", scales: ['2'], lang: 'en' },
    { number: 132, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 133, text: "I do not like conflicts", scales: ['5'], lang: 'en' },
    { number: 134, text: "I sometimes feel helpless", scales: ['K', '5', '9'], lang: 'en' },
    { number: 135, text: "I always try to be neat", scales: ['L'], lang: 'en' },
    { number: 136, text: "I am worried about my relationships", scales: ['3'], lang: 'en' },
    { number: 137, text: "I do not like being alone", scales: ['3'], lang: 'en' },
    { number: 138, text: "I sometimes break rules", scales: ['K', '2', '4'], lang: 'en' },
    { number: 139, text: "I am worried about my memories", scales: ['F'], lang: 'en' },
    { number: 140, text: "I do not like physical strength", scales: ['5'], lang: 'en' },
    { number: 141, text: "I am worried about my dreams", scales: ['3'], lang: 'en' },
    { number: 142, text: "I sometimes feel out of place", scales: ['K', '2', '4'], lang: 'en' },
    { number: 143, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 144, text: "I do not like dancing", scales: ['5'], lang: 'en' },
    { number: 145, text: "I am worried about my appearance", scales: ['2'], lang: 'en' },
    { number: 146, text: "I believe in fate", scales: ['F'], lang: 'en' },
    { number: 147, text: "I am afraid of enclosed spaces", scales: ['3', '0'], lang: 'en' },
    { number: 148, text: "I rarely feel insecure", scales: ['K'], lang: 'en' },
    { number: 149, text: "I love poetry", scales: ['5'], lang: 'en' },
    { number: 150, text: "I always try to be fair", scales: ['L'], lang: 'en' },
    { number: 151, text: "I get angry when I am deceived", scales: ['F'], lang: 'en' },
    { number: 152, text: "I do not tire quickly", scales: ['2'], lang: 'en' },
    { number: 153, text: "I like knowing important people", scales: ['2'], lang: 'en' },
    { number: 154, text: "I am afraid of heights", scales: ['2'], lang: 'en' },
    { number: 155, text: "I am not concerned about family legal issues", scales: ['1'], lang: 'en' },
    { number: 156, text: "I feel happy when I travel", scales: ['F', '8', '9'], lang: 'en' },
    { number: 157, text: "I do not care about others’ opinions", scales: ['6', '8'], lang: 'en' },
    { number: 158, text: "I feel awkward misbehaving at a party", scales: ['2', '6'], lang: 'en' },
    { number: 159, text: "I have never fainted", scales: ['2', '6'], lang: 'en' },
    { number: 160, text: "I enjoyed school", scales: ['K', '2'], lang: 'en' },
    { number: 161, text: "I often feel shy", scales: ['1'], lang: 'en' },
    { number: 162, text: "Someone has tried to poison me", scales: ['6'], lang: 'en' },
    { number: 163, text: "I am not afraid of snakes", scales: ['1'], lang: 'en' },
    { number: 164, text: "I rarely feel dizzy", scales: ['F', '7'], lang: 'en' },
    { number: 165, text: "I always try to be kind", scales: ['L'], lang: 'en' },
    { number: 166, text: "I do not like risk", scales: ['9'], lang: 'en' },
    { number: 167, text: "I love arguing", scales: ['9'], lang: 'en' },
    { number: 168, text: "I am bothered by strange sounds", scales: ['F', '8'], lang: 'en' },
    { number: 169, text: "I rarely have a sore neck", scales: ['F'], lang: 'en' },
    { number: 170, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 171, text: "I sometimes feel rejected", scales: ['4', '0'], lang: 'en' },
    { number: 172, text: "I am worried about my habits", scales: ['3'], lang: 'en' },
    { number: 173, text: "I do not like long conversations", scales: ['4'], lang: 'en' },
    { number: 174, text: "I am worried about my finances", scales: ['3'], lang: 'en' },
    { number: 175, text: "I rarely have a sore throat", scales: ['1'], lang: 'en' },
    { number: 176, text: "I do not like sports", scales: ['5'], lang: 'en' },
    { number: 177, text: "I rarely have cramps", scales: ['F'], lang: 'en' },
    { number: 178, text: "I am worried about my family", scales: ['2'], lang: 'en' },
    { number: 179, text: "I love theater", scales: ['3', '5'], lang: 'en' },
    { number: 180, text: "I rarely break promises", scales: ['K', '0'], lang: 'en' },
    { number: 181, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 182, text: "I often feel lost", scales: ['2', '7', '8'], lang: 'en' },
    { number: 183, text: "I rarely quarrel", scales: ['K'], lang: 'en' },
    { number: 184, text: "I am worried about my dreams", scales: ['F'], lang: 'en' },
    { number: 185, text: "I rarely have back pain", scales: ['F'], lang: 'en' },
    { number: 186, text: "I am worried about my nerves", scales: ['3'], lang: 'en' },
    { number: 187, text: "I love dancing", scales: ['5'], lang: 'en' },
    { number: 188, text: "I rarely have stomach pain", scales: ['1'], lang: 'en' },
    { number: 189, text: "I am worried about my relationships", scales: ['1', '2', '3'], lang: 'en' },
    { number: 190, text: "I rarely feel dizzy", scales: ['1'], lang: 'en' },
    { number: 191, text: "I am not bothered by my dreams", scales: ['2'], lang: 'en' },
    { number: 192, text: "I rarely have a sore neck", scales: ['1'], lang: 'en' },
    { number: 193, text: "I sometimes think about the past", scales: ['2', '0'], lang: 'en' },
    { number: 194, text: "I love being active", scales: ['8', '9'], lang: 'en' },
    { number: 195, text: "I always try to be patient", scales: ['L'], lang: 'en' },
    { number: 196, text: "I rarely have pains", scales: ['F'], lang: 'en' },
    { number: 197, text: "I am worried about my thoughts", scales: ['F'], lang: 'en' },
    { number: 198, text: "I do not like theater", scales: ['5'], lang: 'en' },
    { number: 199, text: "I rarely have headaches", scales: ['F'], lang: 'en' },
    { number: 200, text: "I am worried about my fears", scales: ['F'], lang: 'en' },
    { number: 201, text: "I am worried about my mistakes", scales: ['3', '0'], lang: 'en' },
    { number: 202, text: "I believe in miracles", scales: ['F', '6', '8'], lang: 'en' },
    { number: 203, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 204, text: "I do not like noise", scales: ['5'], lang: 'en' },
    { number: 205, text: "I am worried about my dreams", scales: ['F'], lang: 'en' },
    { number: 206, text: "I believe in ghosts", scales: ['F'], lang: 'en' },
    { number: 207, text: "I am not worried about my job", scales: ['2'], lang: 'en' },
    { number: 208, text: "I rarely think about the future", scales: ['2'], lang: 'en' },
    { number: 209, text: "I am worried about my fears", scales: ['F'], lang: 'en' },
    { number: 210, text: "I believe in magic", scales: ['F', '8'], lang: 'en' },
    { number: 211, text: "I am worried about my habits", scales: ['F'], lang: 'en' },
    { number: 212, text: "I love being busy", scales: ['8', '9'], lang: 'en' },
    { number: 213, text: "I am worried about my relationships", scales: ['3'], lang: 'en' },
    { number: 214, text: "I do not like dancing", scales: ['5'], lang: 'en' },
    { number: 215, text: "I am worried about my thoughts", scales: ['F', '4'], lang: 'en' },
    { number: 216, text: "I sometimes break rules", scales: ['4'], lang: 'en' },
    { number: 217, text: "I rarely get angry", scales: ['K', '5', '7'], lang: 'en' },
    { number: 218, text: "I am worried about my fears", scales: ['F'], lang: 'en' },
    { number: 219, text: "I do not like arguments", scales: ['5'], lang: 'en' },
    { number: 220, text: "I rarely have back pain", scales: ['F'], lang: 'en' },
    { number: 221, text: "I do not like physical work", scales: ['5'], lang: 'en' },
    { number: 222, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 223, text: "I do not like sports", scales: ['5'], lang: 'en' },
    { number: 224, text: "I sometimes lose my patience", scales: ['4'], lang: 'en' },
    { number: 225, text: "I always try to be honest", scales: ['L'], lang: 'en' },
    { number: 226, text: "I love music", scales: ['5'], lang: 'en' },
    { number: 227, text: "I am worried about my memories", scales: ['F'], lang: 'en' },
    { number: 228, text: "I love competitions", scales: ['9'], lang: 'en' },
    { number: 229, text: "I do not like asking for help", scales: ['5'], lang: 'en' },
    { number: 230, text: "I rarely have stomach pain", scales: ['1'], lang: 'en' },
    { number: 231, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 232, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 233, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 234, text: "I rarely feel weak", scales: ['K'], lang: 'en' },
    { number: 235, text: "I rarely feel sad", scales: ['4'], lang: 'en' },
    { number: 236, text: "I often feel depressed", scales: ['2', '0'], lang: 'en' },
    { number: 237, text: "I rarely get angry", scales: ['4'], lang: 'en' },
    { number: 238, text: "I am worried about my nerves", scales: ['3', '7', '8', '9'], lang: 'en' },
    { number: 239, text: "I sometimes act impulsively", scales: ['4', '5'], lang: 'en' },
    { number: 240, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 241, text: "I am worried about my memory", scales: ['2', '8'], lang: 'en' },
    { number: 242, text: "I am not bothered by my dreams", scales: ['2'], lang: 'en' },
    { number: 243, text: "I rarely have a sore neck", scales: ['1'], lang: 'en' },
    { number: 244, text: "I sometimes lose control", scales: ['4'], lang: 'en' },
    { number: 245, text: "I am worried about my fears", scales: ['F', '4', '8'], lang: 'en' },
    { number: 246, text: "I believe in the supernatural", scales: ['F'], lang: 'en' },
    { number: 247, text: "I am worried about my thoughts", scales: ['F'], lang: 'en' },
    { number: 248, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 249, text: "I do not like dancing", scales: ['5'], lang: 'en' },
    { number: 250, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 251, text: "I love being busy", scales: ['8', '9'], lang: 'en' },
    { number: 252, text: "I am worried about my fears", scales: ['F'], lang: 'en' },
    { number: 253, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 254, text: "I do not like sports", scales: ['5'], lang: 'en' },
    { number: 255, text: "I always try to be polite", scales: ['L'], lang: 'en' },
    { number: 256, text: "I am worried about my memories", scales: ['F'], lang: 'en' },
    { number: 257, text: "I rarely have back pain", scales: ['F'], lang: 'en' },
    { number: 258, text: "I rarely have a sore throat", scales: ['F'], lang: 'en' },
    { number: 259, text: "I often feel lost", scales: ['2', '8'], lang: 'en' },
    { number: 260, text: "I do not like physical work", scales: ['5'], lang: 'en' },
    { number: 261, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 262, text: "I do not like noise", scales: ['5'], lang: 'en' },
    { number: 263, text: "I love being a leader", scales: ['2', '9'], lang: 'en' },
    { number: 264, text: "I do not like large gatherings", scales: ['5'], lang: 'en' },
    { number: 265, text: "I am worried about my habits", scales: ['3'], lang: 'en' },
    { number: 266, text: "I am worried about my fears", scales: ['7', '8', '9'], lang: 'en' },
    { number: 267, text: "I rarely get angry", scales: ['K', '4'], lang: 'en' },
    { number: 268, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 269, text: "I am worried about my thoughts", scales: ['F'], lang: 'en' },
    { number: 270, text: "I am not worried about my job", scales: ['2'], lang: 'en' },
    { number: 271, text: "I love competitions", scales: ['2', '9'], lang: 'en' },
    { number: 272, text: "I rarely have headaches", scales: ['F', 'K'], lang: 'en' },
    { number: 273, text: "I am worried about leg pains", scales: ['1', '8'], lang: 'en' },
    { number: 274, text: "I rarely have stomach pain", scales: ['1'], lang: 'en' },
    { number: 275, text: "I believe in predictions", scales: ['F', '6'], lang: 'en' },
    { number: 276, text: "I rarely have cramps", scales: ['F'], lang: 'en' },
    { number: 277, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 278, text: "I love nature", scales: ['5', '0'], lang: 'en' },
    { number: 279, text: "I am worried about my relationships", scales: ['3'], lang: 'en' },
    { number: 280, text: "I do not like dancing", scales: ['5'], lang: 'en' },
    { number: 281, text: "I rarely have back pain", scales: ['1'], lang: 'en' },
    { number: 282, text: "I love music", scales: ['5'], lang: 'en' },
    { number: 283, text: "I do not like sports", scales: ['5'], lang: 'en' },
    { number: 284, text: "I sometimes think about revenge", scales: ['4', '6', '8'], lang: 'en' },
    { number: 285, text: "I always try to be patient", scales: ['L', '2'], lang: 'en' },
    { number: 286, text: "I am worried about my fears", scales: ['F'], lang: 'en' },
    { number: 287, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 288, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 289, text: "I am worried about my habits", scales: ['3'], lang: 'en' },
    { number: 290, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 291, text: "I am worried about my thoughts", scales: ['F', '6', '8'], lang: 'en' },
    { number: 292, text: "I am worried about my mistakes", scales: ['3', '0'], lang: 'en' },
    { number: 293, text: "I believe in miracles", scales: ['F', '6'], lang: 'en' },
    { number: 294, text: "I rarely worry", scales: ['4'], lang: 'en' },
    { number: 295, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 296, text: "I rarely break promises", scales: ['K', '2', '4'], lang: 'en' },
    { number: 297, text: "I do not like noise", scales: ['5'], lang: 'en' },
    { number: 298, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 299, text: "I believe in the supernatural", scales: ['5', '6'], lang: 'en' },
    { number: 300, text: "I do not like large gatherings", scales: ['5'], lang: 'en' },
    { number: 301, text: "I am worried about my fears", scales: ['7', '8'], lang: 'en' },
    { number: 302, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 303, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 304, text: "I am worried about my relationships", scales: ['7', '0'], lang: 'en' },
    { number: 305, text: "I believe in predictions", scales: ['6', '7', '8'], lang: 'en' },
    { number: 306, text: "I rarely have a sore neck", scales: ['0'], lang: 'en' },
    { number: 307, text: "I am worried about my habits", scales: ['8'], lang: 'en' },
    { number: 308, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 309, text: "I rarely have nightmares", scales: ['0'], lang: 'en' },
    { number: 310, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 311, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 312, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 313, text: "I am not afraid of heights", scales: ['6'], lang: 'en' },
    { number: 314, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 315, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 316, text: "I rarely break rules", scales: ['K', '0'], lang: 'en' },
    { number: 317, text: "I am worried about my thoughts", scales: ['6', '7', '8'], lang: 'en' },
    { number: 318, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 319, text: "I do not like being alone", scales: ['6'], lang: 'en' },
    { number: 320, text: "I am worried about my dreams", scales: ['8'], lang: 'en' },
    { number: 321, text: "I am worried about my mistakes", scales: ['7', '0'], lang: 'en' },
    { number: 322, text: "I rarely have back pain", scales: ['K', '0'], lang: 'en' },
    { number: 323, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 324, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 325, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 326, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 327, text: "I am not afraid of the dark", scales: ['6'], lang: 'en' },
    { number: 328, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 329, text: "I am not worried about my job", scales: ['7'], lang: 'en' },
    { number: 330, text: "I rarely have headaches", scales: ['8'], lang: 'en' },
    { number: 331, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 332, text: "I am worried about my habits", scales: ['8', '0'], lang: 'en' },
    { number: 333, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 334, text: "I am worried about my dreams", scales: ['8'], lang: 'en' },
    { number: 335, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 336, text: "I am worried about my mistakes", scales: ['7', '8'], lang: 'en' },
    { number: 337, text: "I am worried about my fears", scales: ['7'], lang: 'en' },
    { number: 338, text: "I sometimes break rules", scales: ['6'], lang: 'en' },
    { number: 339, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 340, text: "I am worried about my relationships", scales: ['7'], lang: 'en' },
    { number: 341, text: "I believe in miracles", scales: ['6', '8'], lang: 'en' },
    { number: 342, text: "I am worried about my habits", scales: ['7', '0'], lang: 'en' },
    { number: 343, text: "I am worried about my fears", scales: ['7'], lang: 'en' },
    { number: 344, text: "I am worried about my dreams", scales: ['7'], lang: 'en' },
    { number: 345, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 346, text: "I am worried about my mistakes", scales: ['7'], lang: 'en' },
    { number: 347, text: "I am not afraid of enclosed spaces", scales: ['6'], lang: 'en' },
    { number: 348, text: "I do not like being alone", scales: ['6'], lang: 'en' },
    { number: 349, text: "I am worried about my fears", scales: ['7', '8'], lang: 'en' },
    { number: 350, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 351, text: "I am worried about my relationships", scales: ['7'], lang: 'en' },
    { number: 352, text: "I am worried about my habits", scales: ['7', '8'], lang: 'en' },
    { number: 353, text: "I am not worried about my job", scales: ['7'], lang: 'en' },
    { number: 354, text: "I am worried about my dreams", scales: ['8'], lang: 'en' },
    { number: 355, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 356, text: "I am worried about my mistakes", scales: ['7', '8'], lang: 'en' },
    { number: 357, text: "I am worried about my relationships", scales: ['7', '0'], lang: 'en' },
    { number: 358, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 359, text: "I am worried about my dreams", scales: ['7'], lang: 'en' },
    { number: 360, text: "I am worried about my habits", scales: ['7', '8'], lang: 'en' },
    { number: 361, text: "I am worried about my fears", scales: ['7'], lang: 'en' },
    { number: 362, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 363, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 364, text: "I believe in predictions", scales: ['6', '8'], lang: 'en' },
    { number: 365, text: "I am worried about my dreams", scales: ['6'], lang: 'en' },
    { number: 366, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 367, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 368, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 369, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 370, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 371, text: "I rarely have back pain", scales: ['0'], lang: 'en' },
    { number: 372, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 373, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 374, text: "I rarely break promises", scales: ['K'], lang: 'en' },
    { number: 375, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 376, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 377, text: "I am worried about my mistakes", scales: ['0'], lang: 'en' },
    { number: 378, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 379, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 380, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 381, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 382, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 383, text: "I rarely feel weak", scales: ['K', '0'], lang: 'en' },
    { number: 384, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 385, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 386, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 387, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 388, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 389, text: "I am worried about my habits", scales: ['8'], lang: 'en' },
    { number: 390, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 391, text: "I rarely have a sore neck", scales: ['0'], lang: 'en' },
    { number: 392, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 393, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 394, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 395, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 396, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 397, text: "I rarely break promises", scales: ['K'], lang: 'en' },
    { number: 398, text: "I rarely feel insecure", scales: ['K', '0'], lang: 'en' },
    { number: 399, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 400, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 401, text: "I am worried about my mistakes", scales: ['0'], lang: 'en' },
    { number: 402, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 403, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 404, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 405, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 406, text: "I rarely feel weak", scales: ['K'], lang: 'en' },
    { number: 407, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 408, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 409, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 410, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 411, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 412, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 413, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 414, text: "I am worried about my habits", scales: ['0'], lang: 'en' },
    { number: 415, text: "I rarely have back pain", scales: ['0'], lang: 'en' },
    { number: 416, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 417, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 418, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 419, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 420, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 421, text: "I rarely break promises", scales: ['K'], lang: 'en' },
    { number: 422, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 423, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 424, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 425, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 426, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 427, text: "I am worried about my mistakes", scales: ['0'], lang: 'en' },
    { number: 428, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 429, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 430, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 431, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 432, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 433, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 434, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 435, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 436, text: "I am worried about my habits", scales: ['0'], lang: 'en' },
    { number: 437, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 438, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 439, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 440, text: "I rarely have a sore neck", scales: ['0'], lang: 'en' },
    { number: 441, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 442, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 443, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 444, text: "I rarely break promises", scales: ['K'], lang: 'en' },
    { number: 445, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 446, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 447, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 448, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 449, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 450, text: "I am worried about my mistakes", scales: ['0'], lang: 'en' },
    { number: 451, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 452, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 453, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 454, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 455, text: "I am worried about my relationships", scales: ['0'], lang: 'en' },
    { number: 456, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 457, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 458, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 459, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 460, text: "I am worried about my habits", scales: ['8'], lang: 'en' },
    { number: 461, text: "I rarely feel weak", scales: ['K'], lang: 'en' },
    { number: 462, text: "I rarely have back pain", scales: ['0'], lang: 'en' },
    { number: 463, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 464, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 465, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 466, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 467, text: "I am worried about my fears", scales: ['0'], lang: 'en' },
    { number: 468, text: "I rarely break promises", scales: ['K'], lang: 'en' },
    { number: 469, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 470, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 471, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 472, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 473, text: "I am worried about my mistakes", scales: ['0'], lang: 'en' },
    { number: 474, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 475, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 476, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 477, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 478, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 479, text: "I rarely have a sore neck", scales: ['0'], lang: 'en' },
    { number: 480, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 481, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 482, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 483, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 484, text: "I am worried about my habits", scales: ['8'], lang: 'en' },
    { number: 485, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 486, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 487, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 488, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 489, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 490, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 491, text: "I rarely break promises", scales: ['K'], lang: 'en' },
    { number: 492, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 493, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 494, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 495, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 496, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 497, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 498, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 499, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 500, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 501, text: "I rarely have back pain", scales: ['0'], lang: 'en' },
    { number: 502, text: "I rarely feel weak", scales: ['K'], lang: 'en' },
    { number: 503, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 504, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 505, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 506, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 507, text: "I am worried about my habits", scales: ['8'], lang: 'en' },
    { number: 508, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 509, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 510, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 511, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 512, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 513, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 514, text: "I rarely break promises", scales: ['K'], lang: 'en' },
    { number: 515, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 516, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 517, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 518, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 519, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 520, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 521, text: "I am worried about my mistakes", scales: ['0'], lang: 'en' },
    { number: 522, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 523, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 524, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 525, text: "I rarely have a sore neck", scales: ['0'], lang: 'en' },
    { number: 526, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 527, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 528, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 529, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 530, text: "I am worried about my habits", scales: ['8'], lang: 'en' },
    { number: 531, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 532, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 533, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 534, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 535, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 536, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 537, text: "I rarely break promises", scales: ['K'], lang: 'en' },
    { number: 538, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 539, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 540, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 541, text: "I love being busy", scales: ['9'], lang: 'en' },
    { number: 542, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 543, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 544, text: "I love adventures", scales: ['9'], lang: 'en' },
    { number: 545, text: "I am worried about my thoughts", scales: ['8'], lang: 'en' },
    { number: 546, text: "I rarely feel sad", scales: ['2'], lang: 'en' },
    { number: 547, text: "I rarely have back pain", scales: ['0'], lang: 'en' },
    { number: 548, text: "I love being a leader", scales: ['9'], lang: 'en' },
    { number: 549, text: "I am worried about my relationships", scales: ['0'], lang: 'en' },
    { number: 550, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 551, text: "I rarely think about the past", scales: ['0'], lang: 'en' },
    { number: 552, text: "I love taking risks", scales: ['9'], lang: 'en' },
    { number: 553, text: "I am worried about my habits", scales: ['8'], lang: 'en' },
    { number: 554, text: "I rarely quarrel", scales: ['4'], lang: 'en' },
    { number: 555, text: "I love nature", scales: ['5'], lang: 'en' },
    { number: 556, text: "I am not bothered by my dreams", scales: ['0'], lang: 'en' },
    { number: 557, text: "I rarely worry", scales: ['2'], lang: 'en' },
    { number: 558, text: "I love being active", scales: ['9'], lang: 'en' },
    { number: 559, text: "I am worried about my fears", scales: ['8'], lang: 'en' },
    { number: 560, text: "I rarely break promises", scales: ['K'], lang: 'en' },
    { number: 561, text: "I love art", scales: ['5'], lang: 'en' },
    { number: 562, text: "I am not worried about my job", scales: ['0'], lang: 'en' },
    { number: 563, text: "I rarely think about the future", scales: ['0'], lang: 'en' },
    { number: 564, text: "I am worried about my mistakes", scales: ['0'], lang: 'en' },
    { number: 565, text: "I rarely get angry", scales: ['K'], lang: 'en' },
    { number: 566, text: "I love adventures", scales: ['9'], lang: 'en' }
];