export const questions = [    
    { number: 1, text: "Bilimsel ve teknik literatürü okumaktan hoşlanırım", scales: ['5'], lang: 'tr' },
    { number: 2, text: "İyi bir iştahım var", scales: ['2'], lang: 'tr' },
    { number: 3, text: "Genellikle sabahları taze ve dinlenmiş hissederek uyanırım", scales: ['2'], lang: 'tr' },
    { number: 4, text: "Kütüphaneci olarak çalışmaktan hoşlanacağımı düşünüyorum", scales: ['5'], lang: 'tr' },
    { number: 5, text: "En ufak bir gürültü beni uyandırır", scales: ['2'], lang: 'tr' },
    { number: 6, text: "Gazetelerde suç haberlerini okumaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 7, text: "Ellerim ve ayaklarım genellikle yeterince sıcaktır", scales: ['1'], lang: 'tr' },
    { number: 8, text: "Günlük hayatım beni ilgilendiren olaylarla doludur", scales: ['2'], lang: 'tr' },
    { number: 9, text: "Üretkenliğim eskisine göre daha kötü değil", scales: ['2'], lang: 'tr' },
    { number: 10, text: "Sık sık boğazımda bir 'yumru' hissediyorum", scales: ['3', '7'], lang: 'tr' },
    { number: 11, text: "Rüyaların her zaman gerçekleştiğine inanıyorum", scales: ['9'], lang: 'tr' },
    { number: 12, text: "Suçlar ve gizemli maceralar hakkında okumaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 13, text: "Çalışma bana önemli bir çaba gerektiriyor", scales: ['2', '7'], lang: 'tr' },
    { number: 14, text: "Bu maddenin numarası bir çemberle çevrilmeli", scales: [], lang: 'tr' },
    { number: 15, text: "Bazen öyle hoş olmayan düşünceler aklıma geliyor ki, bunları anlatmak daha iyi değil", scales: ['L', '6'], lang: 'tr' },
    { number: 16, text: "Hayatın bana karşı acımasız olduğunu hissediyorum", scales: ['4', '6'], lang: 'tr' },
    { number: 17, text: "Babam iyi bir insandır", scales: ['F'], lang: 'tr' },
    { number: 18, text: "Çok nadiren kabızlık yaşıyorum", scales: ['1'], lang: 'tr' },
    { number: 19, text: "Yeni bir işe başlarken, kiminle iyi ilişkiler kurmam gerektiğini bilmeyi tercih ederim", scales: ['5'], lang: 'tr' },
    { number: 20, text: "Cinsel hayatım tatmin edici", scales: ['F'], lang: 'tr' },
    { number: 21, text: "Bazen evi terk etmek çok istedim", scales: ['4', '6'], lang: 'tr' },
    { number: 22, text: "Bazen kontrol edemediğim kahkaha veya ağlama nöbetleri yaşıyorum", scales: ['6', '7'], lang: 'tr' },
    { number: 23, text: "Beni rahatsız eden bulantı ve kusma nöbetleri yaşıyorum", scales: ['1', '2', '3', '4'], lang: 'tr' },
    { number: 24, text: "Beni anlayan kimsenin olmadığını düşünüyorum", scales: ['4', '6', '8'], lang: 'tr' },
    { number: 25, text: "Şarkıcı olmak isterdim", scales: ['5'], lang: 'tr' },
    { number: 26, text: "Rahatsız edici bir durumda susmak benim için en iyisidir", scales: ['3'], lang: 'tr' },
    { number: 27, text: "Bazen kendimi kötü bir gücün etkisi altında hissediyorum", scales: ['F', '6'], lang: 'tr' },
    { number: 28, text: "Eğer bana haksızlık yapılırsa, prensip olarak buna karşılık vermeliyim", scales: ['4'], lang: 'tr' },
    { number: 29, text: "Haftada birkaç kez mide yanması beni rahatsız ediyor", scales: ['1'], lang: 'tr' },
    { number: 30, text: "Bazen küfretmek istiyorum", scales: ['L', 'K'], lang: 'tr' },
    { number: 31, text: "Neredeyse her gece kabuslar görüyorum", scales: ['F'], lang: 'tr' },
    { number: 32, text: "Belirli bir görev veya işe odaklanmakta zorlandığımı fark ediyorum", scales: ['2', '3', '4', '8'], lang: 'tr' },
    { number: 33, text: "Bu maddenin numarası bir çemberle çevrilmeli", scales: [], lang: 'tr' },
    { number: 34, text: "Çoğu zaman öksürüğüm var", scales: ['F'], lang: 'tr' },
    { number: 35, text: "Eğer insanlar bana karşı komplo kurmasaydı, çok daha fazlasını başarırdım", scales: ['F', '4', '6', '8'], lang: 'tr' },
    { number: 36, text: "Sağlığım hakkında nadiren endişelenirim", scales: ['2', '4'], lang: 'tr' },
    { number: 37, text: "Cinsel hayatımla ilgili davranışlarım yüzünden asla sorun yaşamadım", scales: ['4'], lang: 'tr' },
    { number: 38, text: "Gençliğimde küçük hırsızlıklar yaptığım bir dönem oldu", scales: ['F', '8'], lang: 'tr' },
    { number: 39, text: "Bazen eşyaları kırmak veya tabakları parçalamak istiyorum", scales: ['K'], lang: 'tr' },
    { number: 40, text: "Zamanımın çoğunu oturup hayallere dalarak geçirmeyi tercih ederim", scales: ['F', '8'], lang: 'tr' },
    { number: 41, text: "Günler, haftalar veya hatta aylar süren, hiçbir işe başlayamadığım dönemlerim oldu", scales: ['2', '7', '8'], lang: 'tr' },
    { number: 42, text: "Ailem seçtiğim (veya seçeceğim) işten hoşlanmıyor", scales: ['F', '4'], lang: 'tr' },
    { number: 43, text: "Uyku düzenim kesintili ve huzursuz", scales: ['1', '2', '3'], lang: 'tr' },
    { number: 44, text: "Çoğu zaman başım ağrıyor", scales: ['3'], lang: 'tr' },
    { number: 45, text: "Her zaman doğruyu söylemem", scales: ['L'], lang: 'tr' },
    { number: 46, text: "Zihnim şu anda her zamankinden daha iyi çalışıyor", scales: ['2'], lang: 'tr' },
    { number: 47, text: "Haftada bir veya daha fazla, görünür bir sebep olmadan aniden sıcaklık bastırıyor", scales: ['3'], lang: 'tr' },
    { number: 48, text: "Bu maddenin numarası bir çemberle çevrilmeli", scales: [], lang: 'tr' },
    { number: 49, text: "Neredeyse tüm yasalar kaldırılsaydı daha iyi olurdu", scales: ['F'], lang: 'tr' },
    { number: 50, text: "Bazen ölecekmişim gibi hissediyorum", scales: ['F'], lang: 'tr' },
    { number: 51, text: "Sık sık kaygı hissediyorum", scales: ['2', '7'], lang: 'tr' },
    { number: 52, text: "Kolayca yoruluyorum", scales: ['2', '8'], lang: 'tr' },
    { number: 53, text: "Sanki insanlar sık sık arkamdan konuşuyor gibi hissediyorum", scales: ['F', '6'], lang: 'tr' },
    { number: 54, text: "Nadiren baş dönmesi yaşıyorum", scales: ['F'], lang: 'tr' },
    { number: 55, text: "Sırt ağrılarım beni rahatsız ediyor", scales: ['1', '3'], lang: 'tr' },
    { number: 56, text: "Bazen kendimi güvensiz hissediyorum", scales: ['F'], lang: 'tr' },
    { number: 57, text: "Nadiren insanlarla tartışırım", scales: ['2', 'K'], lang: 'tr' },
    { number: 58, text: "Uykuya dalmakta zorlanıyorum", scales: ['2', '7'], lang: 'tr' },
    { number: 59, text: "Canlı sohbetlerden hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 60, text: "Her zaman verdiğim sözleri tutmam", scales: ['L'], lang: 'tr' },
    { number: 61, text: "Bazen sabrımı kaybediyorum", scales: ['4'], lang: 'tr' },
    { number: 62, text: "Sık sık mide ağrılarım oluyor", scales: ['1'], lang: 'tr' },
    { number: 63, text: "Bu maddenin numarası bir çemberle çevrilmeli", scales: [], lang: 'tr' },
    { number: 64, text: "Dikkatlerin merkezinde olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 65, text: "Nadiren zayıflık nöbetleri yaşıyorum", scales: ['F'], lang: 'tr' },
    { number: 66, text: "Bu maddenin numarası bir çemberle çevrilmeli", scales: [], lang: 'tr' },
    { number: 67, text: "Kendimi depresif hissediyorum", scales: ['2', '4', '8'], lang: 'tr' },
    { number: 68, text: "Eklem ağrılarım beni rahatsız ediyor", scales: ['1'], lang: 'tr' },
    { number: 69, text: "Sanatçı olmak isterdim", scales: ['5'], lang: 'tr' },
    { number: 70, text: "Sessiz bir işi tercih ederim", scales: ['5'], lang: 'tr' },
    { number: 71, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 72, text: "Kalp çarpıntısı nöbetlerim oluyor", scales: ['1'], lang: 'tr' },
    { number: 73, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 74, text: "Emir vermekten hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 75, text: "Her zaman kibar olmaya çalışırım", scales: ['L'], lang: 'tr' },
    { number: 76, text: "Göğsümde ağrılar hissediyorum", scales: ['3', '7', '8'], lang: 'tr' },
    { number: 77, text: "Tartışmaktan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 78, text: "Yalnızlığı tercih ederim", scales: ['5'], lang: 'tr' },
    { number: 79, text: "Nadiren hasta hissederim", scales: ['5'], lang: 'tr' },
    { number: 80, text: "Gürültücü insanlar beni rahatsız ediyor", scales: ['2'], lang: 'tr' },
    { number: 81, text: "Fiziksel çalışmadan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 82, text: "Bazen kendimi suçlu hissediyorum", scales: ['4', '0'], lang: 'tr' },
    { number: 83, text: "Nadiren baş ağrısı çekerim", scales: ['F'], lang: 'tr' },
    { number: 84, text: "Bazen impulsif davranıyorum", scales: ['4'], lang: 'tr' },
    { number: 85, text: "Garip düşünceler beni rahatsız ediyor", scales: ['F'], lang: 'tr' },
    { number: 86, text: "Sık sık yorgun hissediyorum", scales: ['2', '7'], lang: 'tr' },
    { number: 87, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 88, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 89, text: "Değişikliklerden hoşlanmam", scales: ['K'], lang: 'tr' },
    { number: 90, text: "Her zaman dürüst olmaya çalışırım", scales: ['L'], lang: 'tr' },
    { number: 91, text: "Sevdiklerimle nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 92, text: "Gürültüden hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 93, text: "Yüksekliklerden korkarım", scales: ['6'], lang: 'tr' },
    { number: 94, text: "Sanki beni küçümsüyorlar gibi hissediyorum", scales: ['4', '7'], lang: 'tr' },
    { number: 95, text: "Nadiren ağlarım", scales: ['2'], lang: 'tr' },
    { number: 96, text: "İnsanlara güvenirim", scales: ['K'], lang: 'tr' },
    { number: 97, text: "Aktif olmaktan hoşlanırım", scales: ['8', '9'], lang: 'tr' },
    { number: 98, text: "Hafızam beni endişelendiriyor", scales: ['2'], lang: 'tr' },
    { number: 99, text: "Yardım istemekten hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 100, text: "Kolayca heveslenirim", scales: ['9'], lang: 'tr' },
    { number: 101, text: "Nadiren yalnız hissederim", scales: ['9'], lang: 'tr' },
    { number: 102, text: "Karar vermekte zorlanıyorum", scales: ['4', '7'], lang: 'tr' },
    { number: 103, text: "Nadiren sırt ağrım olur", scales: ['1'], lang: 'tr' },
    { number: 104, text: "Sık sık kendimi yerimde saymaz hissediyorum", scales: ['2', '8'], lang: 'tr' },
    { number: 105, text: "Eleştiriden hoşlanmam", scales: ['L'], lang: 'tr' },
    { number: 106, text: "Bazen intikam düşüncesi aklıma geliyor", scales: ['4', '7'], lang: 'tr' },
    { number: 107, text: "Sinirlerim beni endişelendiriyor", scales: ['2'], lang: 'tr' },
    { number: 108, text: "Bacak ağrılarım var", scales: ['1'], lang: 'tr' },
    { number: 109, text: "Karanlıktan korkarım", scales: ['6'], lang: 'tr' },
    { number: 110, text: "Bazen kendimi istenmeyen hissediyorum", scales: ['4', '6'], lang: 'tr' },
    { number: 111, text: "Doğaüstüye inanırım", scales: ['6', '0'], lang: 'tr' },
    { number: 112, text: "Nadiren boğaz ağrım olur", scales: ['F'], lang: 'tr' },
    { number: 113, text: "Temizlik yapmaktan hoşlanmam", scales: ['F'], lang: 'tr' },
    { number: 114, text: "Mide ağrılarım beni rahatsız ediyor", scales: ['1', '3'], lang: 'tr' },
    { number: 115, text: "Nadiren yorgun hissederim", scales: ['F'], lang: 'tr' },
    { number: 116, text: "Kamuya açık konuşmalardan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 117, text: "Bazen ölüm düşüncesi aklıma geliyor", scales: ['6', '0'], lang: 'tr' },
    { number: 118, text: "Kolayca sinirlenirim", scales: ['4'], lang: 'tr' },
    { number: 119, text: "Nadiren kabus görürüm", scales: ['F'], lang: 'tr' },
    { number: 120, text: "Büyük kalabalıklardan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 121, text: "Garip düşünceler peşimi bırakmıyor", scales: ['F', '6'], lang: 'tr' },
    { number: 122, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 123, text: "Kehanetlere inanırım", scales: ['F', '6'], lang: 'tr' },
    { number: 124, text: "Nadiren ağrı hissederim", scales: ['K', '0'], lang: 'tr' },
    { number: 125, text: "Kol ağrılarım var", scales: ['1'], lang: 'tr' },
    { number: 126, text: "Müzik severim", scales: ['5'], lang: 'tr' },
    { number: 127, text: "Bazen kontrolümü kaybediyorum", scales: ['4', '9'], lang: 'tr' },
    { number: 128, text: "Fiziksel egzersizden hoşlanmam", scales: ['3'], lang: 'tr' },
    { number: 129, text: "Nadiren kendimi zayıf hissederim", scales: ['K'], lang: 'tr' },
    { number: 130, text: "Sık sık üzgün hissederim", scales: ['2', '9'], lang: 'tr' },
    { number: 131, text: "Rüyalarım beni rahatsız etmiyor", scales: ['2'], lang: 'tr' },
    { number: 132, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 133, text: "Çatışmalardan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 134, text: "Bazen kendimi çaresiz hissediyorum", scales: ['K', '5', '9'], lang: 'tr' },
    { number: 135, text: "Her zaman düzenli olmaya çalışırım", scales: ['L'], lang: 'tr' },
    { number: 136, text: "İlişkilerim beni endişelendiriyor", scales: ['3'], lang: 'tr' },
    { number: 137, text: "Yalnızlıktan hoşlanmam", scales: ['3'], lang: 'tr' },
    { number: 138, text: "Bazen kuralları çiğniyorum", scales: ['K', '2', '4'], lang: 'tr' },
    { number: 139, text: "Anılarım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 140, text: "Fiziksel güçten hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 141, text: "Rüyalarım beni endişelendiriyor", scales: ['3'], lang: 'tr' },
    { number: 142, text: "Bazen kendimi yerimde saymaz hissediyorum", scales: ['K', '2', '4'], lang: 'tr' },
    { number: 143, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 144, text: "Dans etmekten hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 145, text: "Dış görünüşüm beni endişelendiriyor", scales: ['2'], lang: 'tr' },
    { number: 146, text: "Kadere inanırım", scales: ['F'], lang: 'tr' },
    { number: 147, text: "Kapalı alanlardan korkarım", scales: ['3', '0'], lang: 'tr' },
    { number: 148, text: "Nadiren kendimi güvensiz hissederim", scales: ['K'], lang: 'tr' },
    { number: 149, text: "Şiiri severim", scales: ['5'], lang: 'tr' },
    { number: 150, text: "Her zaman adil olmaya çalışırım", scales: ['L'], lang: 'tr' },
    { number: 151, text: "Aldatıldığımda sinirlenirim", scales: ['F'], lang: 'tr' },
    { number: 152, text: "Hızlı yorulmam", scales: ['2'], lang: 'tr' },
    { number: 153, text: "Önemli insanları tanımaktan hoşlanırım", scales: ['2'], lang: 'tr' },
    { number: 154, text: "Yüksekliklerden korkarım", scales: ['2'], lang: 'tr' },
    { number: 155, text: "Ailemin hukuki sorunları beni endişelendirmiyor", scales: ['1'], lang: 'tr' },
    { number: 156, text: "Seyahat ettiğimde mutlu hissediyorum", scales: ['F', '8', '9'], lang: 'tr' },
    { number: 157, text: "Başkalarının görüşleri beni ilgilendirmez", scales: ['6', '8'], lang: 'tr' },
    { number: 158, text: "Partide yaramazlık yapmaktan utanırım", scales: ['2', '6'], lang: 'tr' },
    { number: 159, text: "Hiç bayılmadım", scales: ['2', '6'], lang: 'tr' },
    { number: 160, text: "Okulu seviyordum", scales: ['K', '2'], lang: 'tr' },
    { number: 161, text: "Sık sık utanıyorum", scales: ['1'], lang: 'tr' },
    { number: 162, text: "Biri beni zehirlemeye çalıştı", scales: ['6'], lang: 'tr' },
    { number: 163, text: "Yılanlardan korkmam", scales: ['1'], lang: 'tr' },
    { number: 164, text: "Nadiren baş dönmesi yaşıyorum", scales: ['F', '7'], lang: 'tr' },
    { number: 165, text: "Her zaman nazik olmaya çalışırım", scales: ['L'], lang: 'tr' },
    { number: 166, text: "Riskten hoşlanmam", scales: ['9'], lang: 'tr' },
    { number: 167, text: "Tartışmayı severim", scales: ['9'], lang: 'tr' },
    { number: 168, text: "Garip sesler beni rahatsız ediyor", scales: ['F', '8'], lang: 'tr' },
    { number: 169, text: "Nadiren boyun ağrım olur", scales: ['F'], lang: 'tr' },
    { number: 170, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 171, text: "Bazen kendimi reddedilmiş hissediyorum", scales: ['4', '0'], lang: 'tr' },
    { number: 172, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['3'], lang: 'tr' },
    { number: 173, text: "Uzun sohbetlerden hoşlanmam", scales: ['4'], lang: 'tr' },
    { number: 174, text: "Mali durumum beni endişelendiriyor", scales: ['3'], lang: 'tr' },
    { number: 175, text: "Nadiren boğaz ağrım olur", scales: ['1'], lang: 'tr' },
    { number: 176, text: "Spor yapmaktan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 177, text: "Nadiren kramplar yaşıyorum", scales: ['F'], lang: 'tr' },
    { number: 178, text: "Ailem beni endişelendiriyor", scales: ['2'], lang: 'tr' },
    { number: 179, text: "Tiyatroyu severim", scales: ['3', '5'], lang: 'tr' },
    { number: 180, text: "Nadiren verdiğim sözleri bozarım", scales: ['K', '0'], lang: 'tr' },
    { number: 181, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 182, text: "Sık sık kendimi kaybolmuş hissediyorum", scales: ['2', '7', '8'], lang: 'tr' },
    { number: 183, text: "Nadiren kavga ederim", scales: ['K'], lang: 'tr' },
    { number: 184, text: "Rüyalarım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 185, text: "Nadiren sırt ağrım olur", scales: ['F'], lang: 'tr' },
    { number: 186, text: "Sinirlerim beni endişelendiriyor", scales: ['3'], lang: 'tr' },
    { number: 187, text: "Dans etmeyi severim", scales: ['5'], lang: 'tr' },
    { number: 188, text: "Nadiren mide ağrım olur", scales: ['1'], lang: 'tr' },
    { number: 189, text: "İlişkilerim beni endişelendiriyor", scales: ['1', '2', '3'], lang: 'tr' },
    { number: 190, text: "Nadiren baş dönmesi yaşıyorum", scales: ['1'], lang: 'tr' },
    { number: 191, text: "Rüyalarım beni rahatsız etmiyor", scales: ['2'], lang: 'tr' },
    { number: 192, text: "Nadiren boyun ağrım olur", scales: ['1'], lang: 'tr' },
    { number: 193, text: "Bazen geçmiş hakkında düşünürüm", scales: ['2', '0'], lang: 'tr' },
    { number: 194, text: "Aktif olmaktan hoşlanırım", scales: ['8', '9'], lang: 'tr' },
    { number: 195, text: "Her zaman sabırlı olmaya çalışırım", scales: ['L'], lang: 'tr' },
    { number: 196, text: "Nadiren ağrı çekerim", scales: ['F'], lang: 'tr' },
    { number: 197, text: "Düşüncelerim beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 198, text: "Tiyatrodan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 199, text: "Nadiren baş ağrım olur", scales: ['F'], lang: 'tr' },
    { number: 200, text: "Korkularım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 201, text: "Hatalarım beni endişelendiriyor", scales: ['3', '0'], lang: 'tr' },
    { number: 202, text: "Mucizelere inanırım", scales: ['F', '6', '8'], lang: 'tr' },
    { number: 203, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 204, text: "Gürültüden hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 205, text: "Rüyalarım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 206, text: "Hayaletlere inanırım", scales: ['F'], lang: 'tr' },
    { number: 207, text: "İşim beni endişelendirmiyor", scales: ['2'], lang: 'tr' },
    { number: 208, text: "Nadiren gelecek hakkında düşünürüm", scales: ['2'], lang: 'tr' },
    { number: 209, text: "Korkularım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 210, text: "Büyüye inanırım", scales: ['F', '8'], lang: 'tr' },
    { number: 211, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 212, text: "Meşgul olmaktan hoşlanırım", scales: ['8', '9'], lang: 'tr' },
    { number: 213, text: "İlişkilerim beni endişelendiriyor", scales: ['3'], lang: 'tr' },
    { number: 214, text: "Dans etmekten hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 215, text: "Düşüncelerim beni endişelendiriyor", scales: ['F', '4'], lang: 'tr' },
    { number: 216, text: "Bazen kuralları çiğniyorum", scales: ['4'], lang: 'tr' },
    { number: 217, text: "Nadiren sinirlenirim", scales: ['K', '5', '7'], lang: 'tr' },
    { number: 218, text: "Korkularım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 219, text: "Tartışmalardan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 220, text: "Nadiren sırt ağrım olur", scales: ['F'], lang: 'tr' },
    { number: 221, text: "Fiziksel çalışmadan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 222, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 223, text: "Spor yapmaktan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 224, text: "Bazen sabrımı kaybediyorum", scales: ['4'], lang: 'tr' },
    { number: 225, text: "Her zaman dürüst olmaya çalışırım", scales: ['L'], lang: 'tr' },
    { number: 226, text: "Müzik severim", scales: ['5'], lang: 'tr' },
    { number: 227, text: "Anılarım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 228, text: "Yarışmaları severim", scales: ['9'], lang: 'tr' },
    { number: 229, text: "Yardım istemekten hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 230, text: "Nadiren mide ağrım olur", scales: ['1'], lang: 'tr' },
    { number: 231, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 232, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 233, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 234, text: "Nadiren kendimi zayıf hissederim", scales: ['K'], lang: 'tr' },
    { number: 235, text: "Nadiren üzgün hissederim", scales: ['4'], lang: 'tr' },
    { number: 236, text: "Sık sık kendimi depresif hissediyorum", scales: ['2', '0'], lang: 'tr' },
    { number: 237, text: "Nadiren sinirlenirim", scales: ['4'], lang: 'tr' },
    { number: 238, text: "Sinirlerim beni endişelendiriyor", scales: ['3', '7', '8', '9'], lang: 'tr' },
    { number: 239, text: "Bazen impulsif davranıyorum", scales: ['4', '5'], lang: 'tr' },
    { number: 240, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 241, text: "Hafızam beni endişelendiriyor", scales: ['2', '8'], lang: 'tr' },
    { number: 242, text: "Rüyalarım beni rahatsız etmiyor", scales: ['2'], lang: 'tr' },
    { number: 243, text: "Nadiren boyun ağrım olur", scales: ['1'], lang: 'tr' },
    { number: 244, text: "Bazen kontrolümü kaybediyorum", scales: ['4'], lang: 'tr' },
    { number: 245, text: "Korkularım beni endişelendiriyor", scales: ['F', '4', '8'], lang: 'tr' },
    { number: 246, text: "Doğaüstüye inanırım", scales: ['F'], lang: 'tr' },
    { number: 247, text: "Düşüncelerim beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 248, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 249, text: "Dans etmekten hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 250, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 251, text: "Meşgul olmaktan hoşlanırım", scales: ['8', '9'], lang: 'tr' },
    { number: 252, text: "Korkularım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 253, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 254, text: "Spor yapmaktan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 255, text: "Her zaman kibar olmaya çalışırım", scales: ['L'], lang: 'tr' },
    { number: 256, text: "Anılarım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 257, text: "Nadiren sırt ağrım olur", scales: ['F'], lang: 'tr' },
    { number: 258, text: "Nadiren boğaz ağrım olur", scales: ['F'], lang: 'tr' },
    { number: 259, text: "Sık sık kendimi kaybolmuş hissediyorum", scales: ['2', '8'], lang: 'tr' },
    { number: 260, text: "Fiziksel çalışmadan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 261, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 262, text: "Gürültüden hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 263, text: "Lider olmaktan hoşlanırım", scales: ['2', '9'], lang: 'tr' },
    { number: 264, text: "Büyük kalabalıklardan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 265, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['3'], lang: 'tr' },
    { number: 266, text: "Korkularım beni endişelendiriyor", scales: ['7', '8', '9'], lang: 'tr' },
    { number: 267, text: "Nadiren sinirlenirim", scales: ['K', '4'], lang: 'tr' },
    { number: 268, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 269, text: "Düşüncelerim beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 270, text: "İşim beni endişelendirmiyor", scales: ['2'], lang: 'tr' },
    { number: 271, text: "Yarışmaları severim", scales: ['2', '9'], lang: 'tr' },
    { number: 272, text: "Nadiren baş ağrım olur", scales: ['F', 'K'], lang: 'tr' },
    { number: 273, text: "Bacak ağrılarım beni endişelendiriyor", scales: ['1', '8'], lang: 'tr' },
    { number: 274, text: "Nadiren mide ağrım olur", scales: ['1'], lang: 'tr' },
    { number: 275, text: "Kehanetlere inanırım", scales: ['F', '6'], lang: 'tr' },
    { number: 276, text: "Nadiren kramplar yaşıyorum", scales: ['F'], lang: 'tr' },
    { number: 277, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 278, text: "Doğayı severim", scales: ['5', '0'], lang: 'tr' },
    { number: 279, text: "İlişkilerim beni endişelendiriyor", scales: ['3'], lang: 'tr' },
    { number: 280, text: "Dans etmekten hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 281, text: "Nadiren sırt ağrım olur", scales: ['1'], lang: 'tr' },
    { number: 282, text: "Müzik severim", scales: ['5'], lang: 'tr' },
    { number: 283, text: "Spor yapmaktan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 284, text: "Bazen intikam düşüncesi aklıma geliyor", scales: ['4', '6', '8'], lang: 'tr' },
    { number: 285, text: "Her zaman sabırlı olmaya çalışırım", scales: ['L', '2'], lang: 'tr' },
    { number: 286, text: "Korkularım beni endişelendiriyor", scales: ['F'], lang: 'tr' },
    { number: 287, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 288, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 289, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['3'], lang: 'tr' },
    { number: 290, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 291, text: "Düşüncelerim beni endişelendiriyor", scales: ['F', '6', '8'], lang: 'tr' },
    { number: 292, text: "Hatalarım beni endişelendiriyor", scales: ['3', '0'], lang: 'tr' },
    { number: 293, text: "Mucizelere inanırım", scales: ['F', '6'], lang: 'tr' },
    { number: 294, text: "Nadiren endişelenirim", scales: ['4'], lang: 'tr' },
    { number: 295, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 296, text: "Nadiren verdiğim sözleri bozarım", scales: ['K', '2', '4'], lang: 'tr' },
    { number: 297, text: "Gürültüden hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 298, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 299, text: "Doğaüstüye inanırım", scales: ['5', '6'], lang: 'tr' },
    { number: 300, text: "Büyük kalabalıklardan hoşlanmam", scales: ['5'], lang: 'tr' },
    { number: 301, text: "Korkularım beni endişelendiriyor", scales: ['7', '8'], lang: 'tr' },
    { number: 302, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 303, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 304, text: "İlişkilerim beni endişelendiriyor", scales: ['7', '0'], lang: 'tr' },
    { number: 305, text: "Kehanetlere inanırım", scales: ['6', '7', '8'], lang: 'tr' },
    { number: 306, text: "Nadiren boyun ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 307, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 308, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 309, text: "Nadiren kabus görürüm", scales: ['0'], lang: 'tr' },
    { number: 310, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 311, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 312, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 313, text: "Yüksekliklerden korkmam", scales: ['6'], lang: 'tr' },
    { number: 314, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 315, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 316, text: "Nadiren kuralları çiğnerim", scales: ['K', '0'], lang: 'tr' },
    { number: 317, text: "Düşüncelerim beni endişelendiriyor", scales: ['6', '7', '8'], lang: 'tr' },
    { number: 318, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 319, text: "Yalnızlıktan hoşlanmam", scales: ['6'], lang: 'tr' },
    { number: 320, text: "Rüyalarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 321, text: "Hatalarım beni endişelendiriyor", scales: ['7', '0'], lang: 'tr' },
    { number: 322, text: "Nadiren sırt ağrım olur", scales: ['K', '0'], lang: 'tr' },
    { number: 323, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 324, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 325, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 326, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 327, text: "Karanlıktan korkmam", scales: ['6'], lang: 'tr' },
    { number: 328, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 329, text: "İşim beni endişelendirmiyor", scales: ['7'], lang: 'tr' },
    { number: 330, text: "Nadiren baş ağrım olur", scales: ['8'], lang: 'tr' },
    { number: 331, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 332, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['8', '0'], lang: 'tr' },
    { number: 333, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 334, text: "Rüyalarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 335, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 336, text: "Hatalarım beni endişelendiriyor", scales: ['7', '8'], lang: 'tr' },
    { number: 337, text: "Korkularım beni endişelendiriyor", scales: ['7'], lang: 'tr' },
    { number: 338, text: "Bazen kuralları çiğniyorum", scales: ['6'], lang: 'tr' },
    { number: 339, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 340, text: "İlişkilerim beni endişelendiriyor", scales: ['7'], lang: 'tr' },
    { number: 341, text: "Mucizelere inanırım", scales: ['6', '8'], lang: 'tr' },
    { number: 342, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['7', '0'], lang: 'tr' },
    { number: 343, text: "Korkularım beni endişelendiriyor", scales: ['7'], lang: 'tr' },
    { number: 344, text: "Rüyalarım beni endişelendiriyor", scales: ['7'], lang: 'tr' },
    { number: 345, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 346, text: "Hatalarım beni endişelendiriyor", scales: ['7'], lang: 'tr' },
    { number: 347, text: "Kapalı alanlardan korkmam", scales: ['6'], lang: 'tr' },
    { number: 348, text: "Yalnızlıktan hoşlanmam", scales: ['6'], lang: 'tr' },
    { number: 349, text: "Korkularım beni endişelendiriyor", scales: ['7', '8'], lang: 'tr' },
    { number: 350, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 351, text: "İlişkilerim beni endişelendiriyor", scales: ['7'], lang: 'tr' },
    { number: 352, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['7', '8'], lang: 'tr' },
    { number: 353, text: "İşim beni endişelendirmiyor", scales: ['7'], lang: 'tr' },
    { number: 354, text: "Rüyalarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 355, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 356, text: "Hatalarım beni endişelendiriyor", scales: ['7', '8'], lang: 'tr' },
    { number: 357, text: "İlişkilerim beni endişelendiriyor", scales: ['7', '0'], lang: 'tr' },
    { number: 358, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 359, text: "Rüyalarım beni endişelendiriyor", scales: ['7'], lang: 'tr' },
    { number: 360, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['7', '8'], lang: 'tr' },
    { number: 361, text: "Korkularım beni endişelendiriyor", scales: ['7'], lang: 'tr' },
    { number: 362, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 363, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 364, text: "Kehanetlere inanırım", scales: ['6', '8'], lang: 'tr' },
    { number: 365, text: "Rüyalarım beni endişelendiriyor", scales: ['6'], lang: 'tr' },
    { number: 366, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 367, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 368, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 369, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 370, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 371, text: "Nadiren sırt ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 372, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 373, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 374, text: "Nadiren verdiğim sözleri bozarım", scales: ['K'], lang: 'tr' },
    { number: 375, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 376, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 377, text: "Hatalarım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 378, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 379, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 380, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 381, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 382, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 383, text: "Nadiren kendimi zayıf hissederim", scales: ['K', '0'], lang: 'tr' },
    { number: 384, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 385, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 386, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 387, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 388, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 389, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 390, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 391, text: "Nadiren boyun ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 392, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 393, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 394, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 395, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 396, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 397, text: "Nadiren verdiğim sözleri bozarım", scales: ['K'], lang: 'tr' },
    { number: 398, text: "Nadiren kendimi güvensiz hissederim", scales: ['K', '0'], lang: 'tr' },
    { number: 399, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 400, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 401, text: "Hatalarım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 402, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 403, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 404, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 405, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 406, text: "Nadiren kendimi zayıf hissederim", scales: ['K'], lang: 'tr' },
    { number: 407, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 408, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 409, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 410, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 411, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 412, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 413, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 414, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 415, text: "Nadiren sırt ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 416, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 417, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 418, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 419, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 420, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 421, text: "Nadiren verdiğim sözleri bozarım", scales: ['K'], lang: 'tr' },
    { number: 422, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 423, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 424, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 425, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 426, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 427, text: "Hatalarım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 428, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 429, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 430, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 431, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 432, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 433, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 434, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 435, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 436, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 437, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 438, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 439, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 440, text: "Nadiren boyun ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 441, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 442, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 443, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 444, text: "Nadiren verdiğim sözleri bozarım", scales: ['K'], lang: 'tr' },
    { number: 445, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 446, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 447, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 448, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 449, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 450, text: "Hatalarım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 451, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 452, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 453, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 454, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 455, text: "İlişkilerim beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 456, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 457, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 458, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 459, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 460, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 461, text: "Nadiren kendimi zayıf hissederim", scales: ['K'], lang: 'tr' },
    { number: 462, text: "Nadiren sırt ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 463, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 464, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 465, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 466, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 467, text: "Korkularım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 468, text: "Nadiren verdiğim sözleri bozarım", scales: ['K'], lang: 'tr' },
    { number: 469, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 470, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 471, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 472, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 473, text: "Hatalarım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 474, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 475, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 476, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 477, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 478, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 479, text: "Nadiren boyun ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 480, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 481, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 482, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 483, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 484, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 485, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 486, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 487, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 488, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 489, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 490, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 491, text: "Nadiren verdiğim sözleri bozarım", scales: ['K'], lang: 'tr' },
    { number: 492, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 493, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 494, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 495, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 496, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 497, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 498, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 499, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 500, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 501, text: "Nadiren sırt ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 502, text: "Nadiren kendimi zayıf hissederim", scales: ['K'], lang: 'tr' },
    { number: 503, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 504, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 505, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 506, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 507, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 508, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 509, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 510, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 511, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 512, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 513, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 514, text: "Nadiren verdiğim sözleri bozarım", scales: ['K'], lang: 'tr' },
    { number: 515, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 516, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 517, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 518, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 519, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 520, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 521, text: "Hatalarım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 522, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 523, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 524, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 525, text: "Nadiren boyun ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 526, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 527, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 528, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 529, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 530, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 531, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 532, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 533, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 534, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 535, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 536, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 537, text: "Nadiren verdiğim sözleri bozarım", scales: ['K'], lang: 'tr' },
    { number: 538, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 539, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 540, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 541, text: "Meşgul olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 542, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 543, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 544, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
    { number: 545, text: "Düşüncelerim beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 546, text: "Nadiren üzgün hissederim", scales: ['2'], lang: 'tr' },
    { number: 547, text: "Nadiren sırt ağrım olur", scales: ['0'], lang: 'tr' },
    { number: 548, text: "Lider olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 549, text: "İlişkilerim beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 550, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 551, text: "Nadiren geçmiş hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 552, text: "Risk almaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 553, text: "Alışkanlıklarım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 554, text: "Nadiren kavga ederim", scales: ['4'], lang: 'tr' },
    { number: 555, text: "Doğayı severim", scales: ['5'], lang: 'tr' },
    { number: 556, text: "Rüyalarım beni rahatsız etmiyor", scales: ['0'], lang: 'tr' },
    { number: 557, text: "Nadiren endişelenirim", scales: ['2'], lang: 'tr' },
    { number: 558, text: "Aktif olmaktan hoşlanırım", scales: ['9'], lang: 'tr' },
    { number: 559, text: "Korkularım beni endişelendiriyor", scales: ['8'], lang: 'tr' },
    { number: 560, text: "Nadiren verdiğim sözleri bozarım", scales: ['K'], lang: 'tr' },
    { number: 561, text: "Sanatı severim", scales: ['5'], lang: 'tr' },
    { number: 562, text: "İşim beni endişelendirmiyor", scales: ['0'], lang: 'tr' },
    { number: 563, text: "Nadiren gelecek hakkında düşünürüm", scales: ['0'], lang: 'tr' },
    { number: 564, text: "Hatalarım beni endişelendiriyor", scales: ['0'], lang: 'tr' },
    { number: 565, text: "Nadiren sinirlenirim", scales: ['K'], lang: 'tr' },
    { number: 566, text: "Maceraları severim", scales: ['9'], lang: 'tr' },
];