export const questions = [
    { number: 1, text: "Я люблю читать научно-техническую литературу", scales: ['5'], lang: 'ru' },
    { number: 2, text: "У меня хороший аппетит", scales: ['2'], lang: 'ru' },
    { number: 3, text: "По утрам я обычно встаю свежим и отдохнувшим", scales: ['2'], lang: 'ru' },
    { number: 4, text: "Думаю, что мне понравилась бы работа библиотекаря", scales: ['5'], lang: 'ru' },
    { number: 5, text: "Малейший шум меня будит", scales: ['2'], lang: 'ru' },
    { number: 6, text: "Я люблю читать в газетах заметки о преступлениях", scales: ['9'], lang: 'ru' },
    { number: 7, text: "Мои руки и ноги обычно достаточно теплые", scales: ['1'], lang: 'ru' },
    { number: 8, text: "Моя повседневная жизнь полна событий, интересующих меня", scales: ['2'], lang: 'ru' },
    { number: 9, text: "Моя работоспособность не хуже, чем была раньше", scales: ['2'], lang: 'ru' },
    { number: 10, text: "Я часто ощущаю «комок» в горле", scales: ['3', '7'], lang: 'ru' },
    { number: 11, text: "Я верю, что сны всегда сбываются", scales: ['9'], lang: 'ru' },
    { number: 12, text: "Я люблю читать о преступлениях и таинственных приключениях", scales: ['9'], lang: 'ru' },
    { number: 13, text: "Работа дается мне ценой значительного напряжения", scales: ['2', '7'], lang: 'ru' },
    { number: 14, text: "Номер данного пункта следует обвести кружочком", scales: [], lang: 'ru' }, // Балласт
    { number: 15, text: "Временами мне в голову приходят такие нехорошие мысли, что о них лучше не рассказывать", scales: ['L', '6'], lang: 'ru' },
    { number: 16, text: "Я считаю, что жизнь ко мне беспощадна", scales: ['4', '6'], lang: 'ru' },
    { number: 17, text: "Мой отец хороший человек", scales: ['F'], lang: 'ru' },
    { number: 18, text: "У меня очень редко бывают запоры", scales: ['1'], lang: 'ru' },
    { number: 19, text: "Поступая на новую работу, я предпочитаю знать, с кем я должен наладить хорошие отношения", scales: ['5'], lang: 'ru' },
    { number: 20, text: "Моя половая жизнь удовлетворительна", scales: ['F'], lang: 'ru' },
    { number: 21, text: "Временами мне очень хотелось покинуть дом", scales: ['4', '6'], lang: 'ru' },
    { number: 22, text: "Временами у меня бывают приступы смеха или плача, которые я не могу контролировать", scales: ['6', '7'], lang: 'ru' },
    { number: 23, text: "Меня беспокоят приступы тошноты и рвоты", scales: ['1', '2', '3', '4'], lang: 'ru' },
    { number: 24, text: "Мне кажется, что нет такого человека, который понимал бы меня", scales: ['4', '6', '8'], lang: 'ru' },
    { number: 25, text: "Я бы хотел быть певцом", scales: ['5'], lang: 'ru' },
    { number: 26, text: "Если я попадаю в неприятное положение, то мне лучше всего держать язык за зубами", scales: ['3'], lang: 'ru' },
    { number: 27, text: "Временами я нахожусь во власти какой-то злой силы", scales: ['F', '6'], lang: 'ru' },
    { number: 28, text: "Если со мной поступают несправедливо, я чувствую, что должен отплатить за это просто из принципа", scales: ['4'], lang: 'ru' },
    { number: 29, text: "Несколько раз в неделю меня беспокоит изжога", scales: ['1'], lang: 'ru' },
    { number: 30, text: "Иногда мне хочется выругаться", scales: ['L', 'K'], lang: 'ru' },
    { number: 31, text: "Кошмарные сны снятся мне почти каждую ночь", scales: ['F'], lang: 'ru' },
    { number: 32, text: "Я замечаю, что мне трудно стало сосредоточиться на определенной задаче или работе", scales: ['2', '3', '4', '8'], lang: 'ru' },
    { number: 33, text: "Номер данного пункта следует обвести кружочком", scales: [], lang: 'ru' }, // Балласт
    { number: 34, text: "Большую часть времени у меня бывает кашель", scales: ['F'], lang: 'ru' },
    { number: 35, text: "Если бы люди не интриговали против меня, я бы добился гораздо большего", scales: ['F', '4', '6', '8'], lang: 'ru' },
    { number: 36, text: "Я редко беспокоюсь о своем здоровье", scales: ['2', '4'], lang: 'ru' },
    { number: 37, text: "У меня никогда не было неприятностей из-за моего поведения, связанного с половой жизнью", scales: ['4'], lang: 'ru' },
    { number: 38, text: "В юности было время, когда я совершал мелкие кражи", scales: ['F', '8'], lang: 'ru' },
    { number: 39, text: "Временами мне хочется ломать вещи, бить посуду", scales: ['K'], lang: 'ru' },
    { number: 40, text: "Я бы предпочел большую часть времени сидеть ничего не делая и мечтать", scales: ['F', '8'], lang: 'ru' },
    { number: 41, text: "У меня бывали такие периоды, тянувшиеся дни, недели или даже месяцы, когда я не мог ни за что взяться, так как не мог включиться в работу", scales: ['2', '7', '8'], lang: 'ru' },
    { number: 42, text: "Моей семье не нравится работа, которую я выбрал (или собираюсь выбрать)", scales: ['F', '4'], lang: 'ru' },
    { number: 43, text: "У меня прерывистый и беспокойный сон", scales: ['1', '2', '3'], lang: 'ru' },
    { number: 44, text: "Большую часть времени у меня болит голова", scales: ['3'], lang: 'ru' },
    { number: 45, text: "Я не всегда говорю правду", scales: ['L'], lang: 'ru' },
    { number: 46, text: "Мой рассудок работает сейчас лучше, чем когда-либо", scales: ['2'], lang: 'ru' },
    { number: 47, text: "Раз в неделю или чаще меня без видимой причины неожиданно «обдает жаром»", scales: ['3'], lang: 'ru' },
    { number: 48, text: "Номер данного пункта следует обвести кружочком", scales: [], lang: 'ru' }, // Балласт
    { number: 49, text: "Было бы лучше, если бы почти все законы отменили", scales: ['F'], lang: 'ru' },
    { number: 50, text: "Временами я чувствую, что умираю", scales: ['F'], lang: 'ru' },
    { number: 51, text: "Я часто испытываю чувство тревоги", scales: ['2', '7'], lang: 'ru' },
    { number: 52, text: "Я легко устаю", scales: ['2', '8'], lang: 'ru' },
    { number: 53, text: "Мне кажется, что люди часто обсуждают меня за спиной", scales: ['F', '6'], lang: 'ru' },
    { number: 54, text: "Я редко испытываю головокружение", scales: ['F'], lang: 'ru' },
    { number: 55, text: "Меня беспокоят боли в спине", scales: ['1', '3'], lang: 'ru' },
    { number: 56, text: "Я иногда чувствую себя неуверенно", scales: ['F'], lang: 'ru' },
    { number: 57, text: "Я редко спорю с людьми", scales: ['2', 'K'], lang: 'ru' },
    { number: 58, text: "Мне трудно засыпать", scales: ['2', '7'], lang: 'ru' },
    { number: 59, text: "Я люблю веселые компании", scales: ['9'], lang: 'ru' },
    { number: 60, text: "Я не всегда держу обещания", scales: ['L'], lang: 'ru' },
    { number: 61, text: "Я иногда теряю терпение", scales: ['4'], lang: 'ru' },
    { number: 62, text: "У меня часто болит живот", scales: ['1'], lang: 'ru' },
    { number: 63, text: "Номер данного пункта следует обвести кружочком", scales: [], lang: 'ru' }, // Балласт
    { number: 64, text: "Я люблю быть в центре внимания", scales: ['9'], lang: 'ru' },
    { number: 65, text: "У меня редко бывают приступы слабости", scales: ['F'], lang: 'ru' },
    { number: 66, text: "Номер данного пункта следует обвести кружочком", scales: [], lang: 'ru' }, // Балласт
    { number: 67, text: "Я чувствую себя подавленным", scales: ['2', '4', '8'], lang: 'ru' },
    { number: 68, text: "Меня беспокоят боли в суставах", scales: ['1'], lang: 'ru' },
    { number: 69, text: "Я бы хотел стать художником", scales: ['5'], lang: 'ru' },
    { number: 70, text: "Я предпочитаю тихую работу", scales: ['5'], lang: 'ru' },
    { number: 71, text: "Я редко теряю самообладание", scales: ['K'], lang: 'ru' },
    { number: 72, text: "У меня бывают приступы сердцебиения", scales: ['1'], lang: 'ru' },
    { number: 73, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 74, text: "Я не люблю командовать", scales: ['5'], lang: 'ru' },
    { number: 75, text: "Я всегда стараюсь быть вежливым", scales: ['L'], lang: 'ru' },
    { number: 76, text: "У меня бывают боли в груди", scales: ['3', '7', '8'], lang: 'ru' },
    { number: 77, text: "Я не люблю спорить", scales: ['5'], lang: 'ru' },
    { number: 78, text: "Я предпочитаю одиночество", scales: ['5'], lang: 'ru' },
    { number: 79, text: "Я редко чувствую себя больным", scales: ['5'], lang: 'ru' },
    { number: 80, text: "Меня раздражают шумные люди", scales: ['2'], lang: 'ru' },
    { number: 81, text: "Я не люблю физическую работу", scales: ['5'], lang: 'ru' },
    { number: 82, text: "Я иногда чувствую себя виноватым", scales: ['4', '0'], lang: 'ru' },
    { number: 83, text: "У меня редко болит голова", scales: ['F'], lang: 'ru' },
    { number: 84, text: "Я иногда поступаю импульсивно", scales: ['4'], lang: 'ru' },
    { number: 85, text: "Меня беспокоят странные мысли", scales: ['F'], lang: 'ru' },
    { number: 86, text: "Я часто чувствую усталость", scales: ['2', '7'], lang: 'ru' },
    { number: 87, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 88, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 89, text: "Я не люблю перемен", scales: ['K'], lang: 'ru' },
    { number: 90, text: "Я всегда стараюсь быть честным", scales: ['L'], lang: 'ru' },
    { number: 91, text: "Я редко ссорюсь с близкими", scales: ['4'], lang: 'ru' },
    { number: 92, text: "Я не люблю шум", scales: ['5'], lang: 'ru' },
    { number: 93, text: "Я боюсь высоты", scales: ['6'], lang: 'ru' },
    { number: 94, text: "Мне кажется, что меня недооценивают", scales: ['4', '7'], lang: 'ru' },
    { number: 95, text: "Я редко плачу", scales: ['2'], lang: 'ru' },
    { number: 96, text: "Я доверяю людям", scales: ['K'], lang: 'ru' },
    { number: 97, text: "Я люблю быть активным", scales: ['8', '9'], lang: 'ru' },
    { number: 98, text: "Меня беспокоит моя память", scales: ['2'], lang: 'ru' },
    { number: 99, text: "Я не люблю просить помощи", scales: ['5'], lang: 'ru' },
    { number: 100, text: "Я легко загораюсь энтузиазмом", scales: ['9'], lang: 'ru' },
    { number: 101, text: "Я редко чувствую себя одиноким", scales: ['9'], lang: 'ru' },
    { number: 102, text: "Мне трудно принимать решения", scales: ['4', '7'], lang: 'ru' },
    { number: 103, text: "У меня редко болит спина", scales: ['1'], lang: 'ru' },
    { number: 104, text: "Я часто чувствую себя не в своей тарелке", scales: ['2', '8'], lang: 'ru' },
    { number: 105, text: "Я не люблю критику", scales: ['L'], lang: 'ru' },
    { number: 106, text: "Я иногда думаю о мести", scales: ['4', '7'], lang: 'ru' },
    { number: 107, text: "Меня беспокоят мои нервы", scales: ['2'], lang: 'ru' },
    { number: 108, text: "У меня бывают боли в ногах", scales: ['1'], lang: 'ru' },
    { number: 109, text: "Я боюсь темноты", scales: ['6'], lang: 'ru' },
    { number: 110, text: "Я иногда чувствую себя ненужным", scales: ['4', '6'], lang: 'ru' },
    { number: 111, text: "Я верю в сверхъестественное", scales: ['6', '0'], lang: 'ru' },
    { number: 112, text: "У меня редко болит горло", scales: ['F'], lang: 'ru' },
    { number: 113, text: "Я не люблю убираться", scales: ['F'], lang: 'ru' },
    { number: 114, text: "Меня беспокоят боли в животе", scales: ['1', '3'], lang: 'ru' },
    { number: 115, text: "Я редко чувствую себя уставшим", scales: ['F'], lang: 'ru' },
    { number: 116, text: "Я не люблю публичные выступления", scales: ['5'], lang: 'ru' },
    { number: 117, text: "Я иногда думаю о смерти", scales: ['6', '0'], lang: 'ru' },
    { number: 118, text: "Я легко раздражаюсь", scales: ['4'], lang: 'ru' },
    { number: 119, text: "У меня редко бывают кошмары", scales: ['F'], lang: 'ru' },
    { number: 120, text: "Я не люблю большие компании", scales: ['5'], lang: 'ru' },
    { number: 121, text: "Меня преследуют странные мысли", scales: ['F', '6'], lang: 'ru' },
    { number: 122, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 123, text: "Я верю в предсказания", scales: ['F', '6'], lang: 'ru' },
    { number: 124, text: "Я редко ощущаю боль", scales: ['K', '0'], lang: 'ru' },
    { number: 125, text: "У меня бывают боли в руках", scales: ['1'], lang: 'ru' },
    { number: 126, text: "Я люблю музыку", scales: ['5'], lang: 'ru' },
    { number: 127, text: "Я иногда теряю контроль", scales: ['4', '9'], lang: 'ru' },
    { number: 128, text: "Я не люблю физические нагрузки", scales: ['3'], lang: 'ru' },
    { number: 129, text: "Я редко чувствую себя слабым", scales: ['K'], lang: 'ru' },
    { number: 130, text: "Я часто грущу", scales: ['2', '9'], lang: 'ru' },
    { number: 131, text: "Меня не беспокоят мои сны", scales: ['2'], lang: 'ru' },
    { number: 132, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 133, text: "Я не люблю конфликты", scales: ['5'], lang: 'ru' },
    { number: 134, text: "Я иногда чувствую себя беспомощным", scales: ['K', '5', '9'], lang: 'ru' },
    { number: 135, text: "Я всегда стараюсь быть аккуратным", scales: ['L'], lang: 'ru' },
    { number: 136, text: "Меня беспокоят мои отношения", scales: ['3'], lang: 'ru' },
    { number: 137, text: "Я не люблю одиночество", scales: ['3'], lang: 'ru' },
    { number: 138, text: "Я иногда нарушаю правила", scales: ['K', '2', '4'], lang: 'ru' },
    { number: 139, text: "Меня беспокоят мои воспоминания", scales: ['F'], lang: 'ru' },
    { number: 140, text: "Я не люблю физическую силу", scales: ['5'], lang: 'ru' },
    { number: 141, text: "Меня беспокоят мои сны", scales: ['3'], lang: 'ru' },
    { number: 142, text: "Я иногда чувствую себя не в своей тарелке", scales: ['K', '2', '4'], lang: 'ru' },
    { number: 143, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 144, text: "Я не люблю танцы", scales: ['5'], lang: 'ru' },
    { number: 145, text: "Меня беспокоит моя внешность", scales: ['2'], lang: 'ru' },
    { number: 146, text: "Я верю в судьбу", scales: ['F'], lang: 'ru' },
    { number: 147, text: "Я боюсь замкнутого пространства", scales: ['3', '0'], lang: 'ru' },
    { number: 148, text: "Я редко чувствую себя неуверенно", scales: ['K'], lang: 'ru' },
    { number: 149, text: "Я люблю поэзию", scales: ['5'], lang: 'ru' },
    { number: 150, text: "Я всегда стараюсь быть справедливым", scales: ['L'], lang: 'ru' },
    { number: 151, text: "Я злюсь, когда меня обманывают", scales: ['F'], lang: 'ru' },
    { number: 152, text: "Я не устаю быстро", scales: ['2'], lang: 'ru' },
    { number: 153, text: "Мне нравится знать важных людей", scales: ['2'], lang: 'ru' },
    { number: 154, text: "Я боюсь высоты", scales: ['2'], lang: 'ru' },
    { number: 155, text: "Меня не волнуют проблемы семьи с законом", scales: ['1'], lang: 'ru' },
    { number: 156, text: "Я счастлив, когда путешествую", scales: ['F', '8', '9'], lang: 'ru' },
    { number: 157, text: "Мнение других меня не волнует", scales: ['6', '8'], lang: 'ru' },
    { number: 158, text: "Мне неловко шалить на вечеринке", scales: ['2', '6'], lang: 'ru' },
    { number: 159, text: "У меня не было обмороков", scales: ['2', '6'], lang: 'ru' },
    { number: 160, text: "Мне нравилось в школе", scales: ['K', '2'], lang: 'ru' },
    { number: 161, text: "Я часто стесняюсь", scales: ['1'], lang: 'ru' },
    { number: 162, text: "Кто-то пытался меня отравить", scales: ['6'], lang: 'ru' },
    { number: 163, text: "Я не боюсь змей", scales: ['1'], lang: 'ru' },
    { number: 164, text: "У меня редко бывает головокружение", scales: ['F', '7'], lang: 'ru' },
    { number: 165, text: "Я всегда стараюсь быть добрым", scales: ['L'], lang: 'ru' },
    { number: 166, text: "Я не люблю риск", scales: ['9'], lang: 'ru' },
    { number: 167, text: "Я люблю спорить", scales: ['9'], lang: 'ru' },
    { number: 168, text: "Меня беспокоят странные звуки", scales: ['F', '8'], lang: 'ru' },
    { number: 169, text: "У меня редко болит шея", scales: ['F'], lang: 'ru' },
    { number: 170, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 171, text: "Я иногда чувствую себя отвергнутым", scales: ['4', '0'], lang: 'ru' },
    { number: 172, text: "Меня беспокоят мои привычки", scales: ['3'], lang: 'ru' },
    { number: 173, text: "Я не люблю долгие разговоры", scales: ['4'], lang: 'ru' },
    { number: 174, text: "Меня беспокоят мои финансы", scales: ['3'], lang: 'ru' },
    { number: 175, text: "У меня редко болит горло", scales: ['1'], lang: 'ru' },
    { number: 176, text: "Я не люблю спорт", scales: ['5'], lang: 'ru' },
    { number: 177, text: "У меня редко бывают судороги", scales: ['F'], lang: 'ru' },
    { number: 178, text: "Меня беспокоит моя семья", scales: ['2'], lang: 'ru' },
    { number: 179, text: "Я люблю театр", scales: ['3', '5'], lang: 'ru' },
    { number: 180, text: "Я редко нарушаю обещания", scales: ['K', '0'], lang: 'ru' },
    { number: 181, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 182, text: "Я часто чувствую себя потерянным", scales: ['2', '7', '8'], lang: 'ru' },
    { number: 183, text: "Я редко ссорюсь", scales: ['K'], lang: 'ru' },
    { number: 184, text: "Меня беспокоят мои мечты", scales: ['F'], lang: 'ru' },
    { number: 185, text: "У меня редко болит спина", scales: ['F'], lang: 'ru' },
    { number: 186, text: "Меня беспокоят мои нервы", scales: ['3'], lang: 'ru' },
    { number: 187, text: "Я люблю танцы", scales: ['5'], lang: 'ru' },
    { number: 188, text: "У меня редко болит живот", scales: ['1'], lang: 'ru' },
    { number: 189, text: "Меня беспокоят мои отношения", scales: ['1', '2', '3'], lang: 'ru' },
    { number: 190, text: "У меня редко бывают головокружения", scales: ['1'], lang: 'ru' },
    { number: 191, text: "Меня не беспокоят мои сны", scales: ['2'], lang: 'ru' },
    { number: 192, text: "У меня редко болит шея", scales: ['1'], lang: 'ru' },
    { number: 193, text: "Я иногда думаю о прошлом", scales: ['2', '0'], lang: 'ru' },
    { number: 194, text: "Я люблю быть активным", scales: ['8', '9'], lang: 'ru' },
    { number: 195, text: "Я всегда стараюсь быть терпеливым", scales: ['L'], lang: 'ru' },
    { number: 196, text: "У меня редко бывают боли", scales: ['F'], lang: 'ru' },
    { number: 197, text: "Меня беспокоят мои мысли", scales: ['F'], lang: 'ru' },
    { number: 198, text: "Я не люблю театр", scales: ['5'], lang: 'ru' },
    { number: 199, text: "У меня редко болит голова", scales: ['F'], lang: 'ru' },
    { number: 200, text: "Меня беспокоят мои страхи", scales: ['F'], lang: 'ru' },
    { number: 201, text: "Меня беспокоят мои ошибки", scales: ['3', '0'], lang: 'ru' },
    { number: 202, text: "Я верю в чудеса", scales: ['F', '6', '8'], lang: 'ru' },
    { number: 203, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 204, text: "Я не люблю шум", scales: ['5'], lang: 'ru' },
    { number: 205, text: "Меня беспокоят мои сны", scales: ['F'], lang: 'ru' },
    { number: 206, text: "Я верю в привидения", scales: ['F'], lang: 'ru' },
    { number: 207, text: "Меня не беспокоит моя работа", scales: ['2'], lang: 'ru' },
    { number: 208, text: "Я редко думаю о будущем", scales: ['2'], lang: 'ru' },
    { number: 209, text: "Меня беспокоят мои страхи", scales: ['F'], lang: 'ru' },
    { number: 210, text: "Я верю в магию", scales: ['F', '8'], lang: 'ru' },
    { number: 211, text: "Меня беспокоят мои привычки", scales: ['F'], lang: 'ru' },
    { number: 212, text: "Я люблю быть занятым", scales: ['8', '9'], lang: 'ru' },
    { number: 213, text: "Меня беспокоят мои отношения", scales: ['3'], lang: 'ru' },
    { number: 214, text: "Я не люблю танцы", scales: ['5'], lang: 'ru' },
    { number: 215, text: "Меня беспокоят мои мысли", scales: ['F', '4'], lang: 'ru' },
    { number: 216, text: "Я иногда нарушаю правила", scales: ['4'], lang: 'ru' },
    { number: 217, text: "Я редко сержусь", scales: ['K', '5', '7'], lang: 'ru' },
    { number: 218, text: "Меня беспокоят мои страхи", scales: ['F'], lang: 'ru' },
    { number: 219, text: "Я не люблю споры", scales: ['5'], lang: 'ru' },
    { number: 220, text: "У меня редко болит спина", scales: ['F'], lang: 'ru' },
    { number: 221, text: "Я не люблю физическую работу", scales: ['5'], lang: 'ru' },
    { number: 222, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 223, text: "Я не люблю спорт", scales: ['5'], lang: 'ru' },
    { number: 224, text: "Я иногда теряю терпение", scales: ['4'], lang: 'ru' },
    { number: 225, text: "Я всегда стараюсь быть честным", scales: ['L'], lang: 'ru' },
    { number: 226, text: "Я люблю музыку", scales: ['5'], lang: 'ru' },
    { number: 227, text: "Меня беспокоят мои воспоминания", scales: ['F'], lang: 'ru' },
    { number: 228, text: "Я люблю соревнования", scales: ['9'], lang: 'ru' },
    { number: 229, text: "Я не люблю просить помощи", scales: ['5'], lang: 'ru' },
    { number: 230, text: "У меня редко болит живот", scales: ['1'], lang: 'ru' },
    { number: 231, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 232, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 233, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 234, text: "Я редко чувствую себя слабым", scales: ['K'], lang: 'ru' },
    { number: 235, text: "Я редко грущу", scales: ['4'], lang: 'ru' },
    { number: 236, text: "Я часто чувствую себя подавленным", scales: ['2', '0'], lang: 'ru' },
    { number: 237, text: "Я редко сержусь", scales: ['4'], lang: 'ru' },
    { number: 238, text: "Меня беспокоят мои нервы", scales: ['3', '7', '8', '9'], lang: 'ru' },
    { number: 239, text: "Я иногда поступаю импульсивно", scales: ['4', '5'], lang: 'ru' },
    { number: 240, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 241, text: "Меня беспокоит моя память", scales: ['2', '8'], lang: 'ru' },
    { number: 242, text: "Меня не беспокоят мои сны", scales: ['2'], lang: 'ru' },
    { number: 243, text: "У меня редко болит шея", scales: ['1'], lang: 'ru' },
    { number: 244, text: "Я иногда теряю контроль", scales: ['4'], lang: 'ru' },
    { number: 245, text: "Меня беспокоят мои страхи", scales: ['F', '4', '8'], lang: 'ru' },
    { number: 246, text: "Я верю в сверхъестественное", scales: ['F'], lang: 'ru' },
    { number: 247, text: "Меня беспокоят мои мысли", scales: ['F'], lang: 'ru' },
    { number: 248, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 249, text: "Я не люблю танцы", scales: ['5'], lang: 'ru' },
    { number: 250, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 251, text: "Я люблю быть занятым", scales: ['8', '9'], lang: 'ru' },
    { number: 252, text: "Меня беспокоят мои страхи", scales: ['F'], lang: 'ru' },
    { number: 253, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 254, text: "Я не люблю спорт", scales: ['5'], lang: 'ru' },
    { number: 255, text: "Я всегда стараюсь быть вежливым", scales: ['L'], lang: 'ru' },
    { number: 256, text: "Меня беспокоят мои воспоминания", scales: ['F'], lang: 'ru' },
    { number: 257, text: "У меня редко болит спина", scales: ['F'], lang: 'ru' },
    { number: 258, text: "У меня редко болит горло", scales: ['F'], lang: 'ru' },
    { number: 259, text: "Я часто чувствую себя потерянным", scales: ['2', '8'], lang: 'ru' },
    { number: 260, text: "Я не люблю физическую работу", scales: ['5'], lang: 'ru' },
    { number: 261, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 262, text: "Я не люблю шум", scales: ['5'], lang: 'ru' },
    { number: 263, text: "Я люблю быть лидером", scales: ['2', '9'], lang: 'ru' },
    { number: 264, text: "Я не люблю большие компании", scales: ['5'], lang: 'ru' },
    { number: 265, text: "Меня беспокоят мои привычки", scales: ['3'], lang: 'ru' },
    { number: 266, text: "Меня беспокоят мои страхи", scales: ['7', '8', '9'], lang: 'ru' },
    { number: 267, text: "Я редко сержусь", scales: ['K', '4'], lang: 'ru' },
    { number: 268, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 269, text: "Меня беспокоят мои мысли", scales: ['F'], lang: 'ru' },
    { number: 270, text: "Меня не беспокоит моя работа", scales: ['2'], lang: 'ru' },
    { number: 271, text: "Я люблю соревнования", scales: ['2', '9'], lang: 'ru' },
    { number: 272, text: "У меня редко болит голова", scales: ['F', 'K'], lang: 'ru' },
    { number: 273, text: "Меня беспокоят боли в ногах", scales: ['1', '8'], lang: 'ru' },
    { number: 274, text: "У меня редко болит живот", scales: ['1'], lang: 'ru' },
    { number: 275, text: "Я верю в предсказания", scales: ['F', '6'], lang: 'ru' },
    { number: 276, text: "У меня редко бывают судороги", scales: ['F'], lang: 'ru' },
    { number: 277, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 278, text: "Я люблю природу", scales: ['5', '0'], lang: 'ru' },
    { number: 279, text: "Меня беспокоят мои отношения", scales: ['3'], lang: 'ru' },
    { number: 280, text: "Я не люблю танцы", scales: ['5'], lang: 'ru' },
    { number: 281, text: "У меня редко болит спина", scales: ['1'], lang: 'ru' },
    { number: 282, text: "Я люблю музыку", scales: ['5'], lang: 'ru' },
    { number: 283, text: "Я не люблю спорт", scales: ['5'], lang: 'ru' },
    { number: 284, text: "Я иногда думаю о мести", scales: ['4', '6', '8'], lang: 'ru' },
    { number: 285, text: "Я всегда стараюсь быть терпеливым", scales: ['L', '2'], lang: 'ru' },
    { number: 286, text: "Меня беспокоят мои страхи", scales: ['F'], lang: 'ru' },
    { number: 287, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 288, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 289, text: "Меня беспокоят мои привычки", scales: ['3'], lang: 'ru' },
    { number: 290, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 291, text: "Меня беспокоят мои мысли", scales: ['F', '6', '8'], lang: 'ru' },
    { number: 292, text: "Меня беспокоят мои ошибки", scales: ['3', '0'], lang: 'ru' },
    { number: 293, text: "Я верю в чудеса", scales: ['F', '6'], lang: 'ru' },
    { number: 294, text: "Я редко волнуюсь", scales: ['4'], lang: 'ru' },
    { number: 295, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 296, text: "Я редко нарушаю обещания", scales: ['K', '2', '4'], lang: 'ru' },
    { number: 297, text: "Я не люблю шум", scales: ['5'], lang: 'ru' },
    { number: 298, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 299, text: "Я верю в сверхъестественное", scales: ['5', '6'], lang: 'ru' },
    { number: 300, text: "Я не люблю большие компании", scales: ['5'], lang: 'ru' },
    { number: 301, text: "Меня беспокоят мои страхи", scales: ['7', '8'], lang: 'ru' },
    { number: 302, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 303, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 304, text: "Меня беспокоят мои отношения", scales: ['7', '0'], lang: 'ru' },
    { number: 305, text: "Я верю в предсказания", scales: ['6', '7', '8'], lang: 'ru' },
    { number: 306, text: "У меня редко болит шея", scales: ['0'], lang: 'ru' },
    { number: 307, text: "Меня беспокоят мои привычки", scales: ['8'], lang: 'ru' },
    { number: 308, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 309, text: "У меня редко бывают кошмары", scales: ['0'], lang: 'ru' },
    { number: 310, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 311, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 312, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 313, text: "Я не боюсь высоты", scales: ['6'], lang: 'ru' },
    { number: 314, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 315, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 316, text: "Я редко нарушаю правила", scales: ['K', '0'], lang: 'ru' },
    { number: 317, text: "Меня беспокоят мои мысли", scales: ['6', '7', '8'], lang: 'ru' },
    { number: 318, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 319, text: "Я не люблю одиночество", scales: ['6'], lang: 'ru' },
    { number: 320, text: "Меня беспокоят мои сны", scales: ['8'], lang: 'ru' },
    { number: 321, text: "Меня беспокоят мои ошибки", scales: ['7', '0'], lang: 'ru' },
    { number: 322, text: "У меня редко болит спина", scales: ['K', '0'], lang: 'ru' },
    { number: 323, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 324, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 325, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 326, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 327, text: "Я не боюсь темноты", scales: ['6'], lang: 'ru' },
    { number: 328, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 329, text: "Меня не беспокоит моя работа", scales: ['7'], lang: 'ru' },
    { number: 330, text: "У меня редко болит голова", scales: ['8'], lang: 'ru' },
    { number: 331, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 332, text: "Меня беспокоят мои привычки", scales: ['8', '0'], lang: 'ru' },
    { number: 333, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 334, text: "Меня беспокоят мои сны", scales: ['8'], lang: 'ru' },
    { number: 335, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 336, text: "Меня беспокоят мои ошибки", scales: ['7', '8'], lang: 'ru' },
    { number: 337, text: "Меня беспокоят мои страхи", scales: ['7'], lang: 'ru' },
    { number: 338, text: "Я иногда нарушаю правила", scales: ['6'], lang: 'ru' },
    { number: 339, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 340, text: "Меня беспокоят мои отношения", scales: ['7'], lang: 'ru' },
    { number: 341, text: "Я верю в чудеса", scales: ['6', '8'], lang: 'ru' },
    { number: 342, text: "Меня беспокоят мои привычки", scales: ['7', '0'], lang: 'ru' },
    { number: 343, text: "Меня беспокоят мои страхи", scales: ['7'], lang: 'ru' },
    { number: 344, text: "Меня беспокоят мои сны", scales: ['7'], lang: 'ru' },
    { number: 345, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 346, text: "Меня беспокоят мои ошибки", scales: ['7'], lang: 'ru' },
    { number: 347, text: "Я не боюсь замкнутого пространства", scales: ['6'], lang: 'ru' },
    { number: 348, text: "Я не люблю одиночество", scales: ['6'], lang: 'ru' },
    { number: 349, text: "Меня беспокоят мои страхи", scales: ['7', '8'], lang: 'ru' },
    { number: 350, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 351, text: "Меня беспокоят мои отношения", scales: ['7'], lang: 'ru' },
    { number: 352, text: "Меня беспокоят мои привычки", scales: ['7', '8'], lang: 'ru' },
    { number: 353, text: "Меня не беспокоит моя работа", scales: ['7'], lang: 'ru' },
    { number: 354, text: "Меня беспокоят мои сны", scales: ['8'], lang: 'ru' },
    { number: 355, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 356, text: "Меня беспокоят мои ошибки", scales: ['7', '8'], lang: 'ru' },
    { number: 357, text: "Меня беспокоят мои отношения", scales: ['7', '0'], lang: 'ru' },
    { number: 358, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 359, text: "Меня беспокоят мои сны", scales: ['7'], lang: 'ru' },
    { number: 360, text: "Меня беспокоят мои привычки", scales: ['7', '8'], lang: 'ru' },
    { number: 361, text: "Меня беспокоят мои страхи", scales: ['7'], lang: 'ru' },
    { number: 362, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 363, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 364, text: "Я верю в предсказания", scales: ['6', '8'], lang: 'ru' },
    { number: 365, text: "Меня беспокоят мои сны", scales: ['6'], lang: 'ru' },
    { number: 366, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 367, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 368, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 369, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 370, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 371, text: "У меня редко болит спина", scales: ['0'], lang: 'ru' },
    { number: 372, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 373, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 374, text: "Я редко нарушаю обещания", scales: ['K'], lang: 'ru' },
    { number: 375, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 376, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 377, text: "Меня беспокоят мои ошибки", scales: ['0'], lang: 'ru' },
    { number: 378, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 379, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 380, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 381, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 382, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 383, text: "Я редко чувствую себя слабым", scales: ['K', '0'], lang: 'ru' },
    { number: 384, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 385, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 386, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 387, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 388, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 389, text: "Меня беспокоят мои привычки", scales: ['8'], lang: 'ru' },
    { number: 390, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 391, text: "У меня редко болит шея", scales: ['0'], lang: 'ru' },
    { number: 392, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 393, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 394, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 395, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 396, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 397, text: "Я редко нарушаю обещания", scales: ['K'], lang: 'ru' },
    { number: 398, text: "Я редко чувствую себя неуверенно", scales: ['K', '0'], lang: 'ru' },
    { number: 399, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 400, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 401, text: "Меня беспокоят мои ошибки", scales: ['0'], lang: 'ru' },
    { number: 402, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 403, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 404, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 405, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 406, text: "Я редко чувствую себя слабым", scales: ['K'], lang: 'ru' },
    { number: 407, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 408, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 409, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 410, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 411, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 412, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 413, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 414, text: "Меня беспокоят мои привычки", scales: ['8'], lang: 'ru' },
    { number: 415, text: "У меня редко болит спина", scales: ['0'], lang: 'ru' },
    { number: 416, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 417, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 418, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 419, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 420, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 421, text: "Я редко нарушаю обещания", scales: ['K'], lang: 'ru' },
    { number: 422, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 423, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 424, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 425, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 426, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 427, text: "Меня беспокоят мои ошибки", scales: ['0'], lang: 'ru' },
    { number: 428, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 429, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 430, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 431, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 432, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 433, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 434, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 435, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 436, text: "Меня беспокоят мои привычки", scales: ['0'], lang: 'ru' },
    { number: 437, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 438, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 439, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 440, text: "У меня редко болит шея", scales: ['0'], lang: 'ru' },
    { number: 441, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 442, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 443, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 444, text: "Я редко нарушаю обещания", scales: ['K'], lang: 'ru' },
    { number: 445, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 446, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 447, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 448, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 449, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 450, text: "Меня беспокоят мои ошибки", scales: ['0'], lang: 'ru' },
    { number: 451, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 452, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 453, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 454, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 455, text: "Меня беспокоят мои отношения", scales: ['0'], lang: 'ru' },
    { number: 456, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 457, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 458, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 459, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 460, text: "Меня беспокоят мои привычки", scales: ['8'], lang: 'ru' },
    { number: 461, text: "Я редко чувствую себя слабым", scales: ['K'], lang: 'ru' },
    { number: 462, text: "У меня редко болит спина", scales: ['0'], lang: 'ru' },
    { number: 463, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 464, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 465, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 466, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 467, text: "Меня беспокоят мои страхи", scales: ['0'], lang: 'ru' },
    { number: 468, text: "Я редко нарушаю обещания", scales: ['K'], lang: 'ru' },
    { number: 469, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 470, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 471, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 472, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 473, text: "Mеня беспокоят мои ошибки", scales: ['0'], lang: 'ru' },
    { number: 474, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 475, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 476, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 477, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 478, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 479, text: "У меня редко болит шея", scales: ['0'], lang: 'ru' },
    { number: 480, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 481, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 482, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 483, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 484, text: "Меня беспокоят мои привычки", scales: ['8'], lang: 'ru' },
    { number: 485, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 486, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 487, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 488, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 489, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 490, text: "Mеня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 491, text: "Я редко нарушаю обещания", scales: ['K'], lang: 'ru' },
    { number: 492, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 493, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 494, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 495, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 496, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 497, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 498, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 499, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 500, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 501, text: "У меня редко болит спина", scales: ['0'], lang: 'ru' },
    { number: 502, text: "Я редко чувствую себя слабым", scales: ['K'], lang: 'ru' },
    { number: 503, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 504, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 505, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 506, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 507, text: "Меня беспокоят мои привычки", scales: ['8'], lang: 'ru' },
    { number: 508, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 509, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 510, text: "Меня не беспокоят мои sны", scales: ['0'], lang: 'ru' },
    { number: 511, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 512, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 513, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 514, text: "Я редко нарушаю обещания", scales: ['K'], lang: 'ru' },
    { number: 515, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 516, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 517, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 518, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 519, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 520, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 521, text: "Меня беспокоят мои ошибки", scales: ['0'], lang: 'ru' },
    { number: 522, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 523, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 524, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 525, text: "У меня редко болит шея", scales: ['0'], lang: 'ru' },
    { number: 526, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 527, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 528, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 529, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 530, text: "Меня беспокоят мои привычки", scales: ['8'], lang: 'ru' },
    { number: 531, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 532, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 533, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 534, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 535, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 536, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 537, text: "Я редко нарушаю обещания", scales: ['K'], lang: 'ru' },
    { number: 538, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 539, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 540, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 541, text: "Я люблю быть занятым", scales: ['9'], lang: 'ru' },
    { number: 542, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 543, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 544, text: "Я люблю приключения", scales: ['9'], lang: 'ru' },
    { number: 545, text: "Меня беспокоят мои мысли", scales: ['8'], lang: 'ru' },
    { number: 546, text: "Я редко грущу", scales: ['2'], lang: 'ru' },
    { number: 547, text: "У меня редко болит спина", scales: ['0'], lang: 'ru' },
    { number: 548, text: "Я люблю быть лидером", scales: ['9'], lang: 'ru' },
    { number: 549, text: "Mеня беспокоят мои отношения", scales: ['0'], lang: 'ru' },
    { number: 550, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 551, text: "Я редко думаю о прошлом", scales: ['0'], lang: 'ru' },
    { number: 552, text: "Я люблю рисковать", scales: ['9'], lang: 'ru' },
    { number: 553, text: "Меня беспокоят мои привычки", scales: ['8'], lang: 'ru' },
    { number: 554, text: "Я редко ссорюсь", scales: ['4'], lang: 'ru' },
    { number: 555, text: "Я люблю природу", scales: ['5'], lang: 'ru' },
    { number: 556, text: "Меня не беспокоят мои сны", scales: ['0'], lang: 'ru' },
    { number: 557, text: "Я редко волнуюсь", scales: ['2'], lang: 'ru' },
    { number: 558, text: "Я люблю быть активным", scales: ['9'], lang: 'ru' },
    { number: 559, text: "Меня беспокоят мои страхи", scales: ['8'], lang: 'ru' },
    { number: 560, text: "Я редко нарушаю обещания", scales: ['K'], lang: 'ru' },
    { number: 561, text: "Я люблю искусство", scales: ['5'], lang: 'ru' },
    { number: 562, text: "Меня не беспокоит моя работа", scales: ['0'], lang: 'ru' },
    { number: 563, text: "Я редко думаю о будущем", scales: ['0'], lang: 'ru' },
    { number: 564, text: "Mеня беспокоят мои ошибки", scales: ['0'], lang: 'ru' },
    { number: 565, text: "Я редко сержусь", scales: ['K'], lang: 'ru' },
    { number: 566, text: "Я люблю приключения", scales: ['9'], lang: 'ru' }
];    